"use strict";
/**
 * Pyramid Analytics Web API
 * Pyramid Analytics Web API enables user applications to manage their pyramid                                             data and settings
 *
 * The version of the OpenAPI document: 2023.12.181
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.AddMeasureOverlayApiObject = void 0;
/**
* An object representing the measure overlays to be applied to a data model.
*/
var AddMeasureOverlayApiObject = /** @class */ (function () {
    function AddMeasureOverlayApiObject() {
    }
    AddMeasureOverlayApiObject.getAttributeTypeMap = function () {
        return AddMeasureOverlayApiObject.attributeTypeMap;
    };
    AddMeasureOverlayApiObject.discriminator = undefined;
    AddMeasureOverlayApiObject.attributeTypeMap = [
        {
            "name": "modelId",
            "baseName": "modelId",
            "type": "string"
        },
        {
            "name": "roleId",
            "baseName": "roleId",
            "type": "string"
        },
        {
            "name": "overlaysToAdd",
            "baseName": "overlaysToAdd",
            "type": "Array<MeasureOverlayData>"
        }
    ];
    return AddMeasureOverlayApiObject;
}());
exports.AddMeasureOverlayApiObject = AddMeasureOverlayApiObject;
