/**
 * Pyramid Analytics Web API
 * Pyramid Analytics Web API enables user applications to manage their pyramid                                             data and settings
 *
 * The version of the OpenAPI document: 2023.12.181
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* An object for defining which users are attached a role.
*/
export class AddUsersRoleData {
    /**
    * The role\'s ID
    */
    'roleId': string;
    /**
    * List of user ID\'s that will be attached to a role
    */
    'userIds': Array<string>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "roleId",
            "baseName": "roleId",
            "type": "string"
        },
        {
            "name": "userIds",
            "baseName": "userIds",
            "type": "Array<string>"
        }    ];

    static getAttributeTypeMap() {
        return AddUsersRoleData.attributeTypeMap;
    }
}

