"use strict";
/**
 * Pyramid Analytics Web API
 * Pyramid Analytics Web API enables user applications to manage their pyramid                                             data and settings
 *
 * The version of the OpenAPI document: 2023.12.181
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.AdminMultiTenantData = void 0;
/**
* The tenant object contains all relevant meta-data for the tenant.
*/
var AdminMultiTenantData = /** @class */ (function () {
    function AdminMultiTenantData() {
    }
    AdminMultiTenantData.getAttributeTypeMap = function () {
        return AdminMultiTenantData.attributeTypeMap;
    };
    AdminMultiTenantData.discriminator = undefined;
    AdminMultiTenantData.attributeTypeMap = [
        {
            "name": "usedViewerSeats",
            "baseName": "usedViewerSeats",
            "type": "number"
        },
        {
            "name": "defaultThemeId",
            "baseName": "defaultThemeId",
            "type": "string"
        },
        {
            "name": "usedAnalystSeats",
            "baseName": "usedAnalystSeats",
            "type": "number"
        },
        {
            "name": "defaultHubTemplateId",
            "baseName": "defaultHubTemplateId",
            "type": "string"
        },
        {
            "name": "scientistSeats",
            "baseName": "scientistSeats",
            "type": "number"
        },
        {
            "name": "usedScientistSeats",
            "baseName": "usedScientistSeats",
            "type": "number"
        },
        {
            "name": "viewerSeats",
            "baseName": "viewerSeats",
            "type": "number"
        },
        {
            "name": "miscSettings",
            "baseName": "miscSettings",
            "type": "TenantSettings"
        },
        {
            "name": "pulseKey",
            "baseName": "pulseKey",
            "type": "string"
        },
        {
            "name": "usedProSeats",
            "baseName": "usedProSeats",
            "type": "number"
        },
        {
            "name": "selectedUserDefaultsId",
            "baseName": "selectedUserDefaultsId",
            "type": "string"
        },
        {
            "name": "basicSeats",
            "baseName": "basicSeats",
            "type": "number"
        },
        {
            "name": "defaultAiServer",
            "baseName": "defaultAiServer",
            "type": "string"
        },
        {
            "name": "proSeats",
            "baseName": "proSeats",
            "type": "number"
        },
        {
            "name": "usedBasicSeats",
            "baseName": "usedBasicSeats",
            "type": "number"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "analystSeats",
            "baseName": "analystSeats",
            "type": "number"
        },
        {
            "name": "isUserDefaultsOverridable",
            "baseName": "isUserDefaultsOverridable",
            "type": "boolean"
        },
        {
            "name": "defaultEmailTemplateId",
            "baseName": "defaultEmailTemplateId",
            "type": "string"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        }
    ];
    return AdminMultiTenantData;
}());
exports.AdminMultiTenantData = AdminMultiTenantData;
