"use strict";
/**
 * Pyramid Analytics Web API
 * Pyramid Analytics Web API enables user applications to manage their pyramid                                             data and settings
 *
 * The version of the OpenAPI document: 2023.12.181
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.AnalyticsPermissions = void 0;
/**
* The functional items to be available in the profile as either a list or a sum index bits. The list will take priority if both are supplied
*/
var AnalyticsPermissions = /** @class */ (function () {
    function AnalyticsPermissions() {
    }
    AnalyticsPermissions.getAttributeTypeMap = function () {
        return AnalyticsPermissions.attributeTypeMap;
    };
    AnalyticsPermissions.discriminator = undefined;
    AnalyticsPermissions.attributeTypeMap = [
        {
            "name": "permissionBitIndexList",
            "baseName": "permissionBitIndexList",
            "type": "Array<AnalystPermissionBitIndex>"
        },
        {
            "name": "numeric",
            "baseName": "numeric",
            "type": "number"
        }
    ];
    return AnalyticsPermissions;
}());
exports.AnalyticsPermissions = AnalyticsPermissions;
