"use strict";
/**
 * Pyramid Analytics Web API
 * Pyramid Analytics Web API enables user applications to manage their pyramid                                             data and settings
 *
 * The version of the OpenAPI document: 2023.12.181
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ApiResultLicenseStatus = void 0;
/**
* An object containing the license status
*/
var ApiResultLicenseStatus = /** @class */ (function () {
    function ApiResultLicenseStatus() {
    }
    ApiResultLicenseStatus.getAttributeTypeMap = function () {
        return ApiResultLicenseStatus.attributeTypeMap;
    };
    ApiResultLicenseStatus.discriminator = undefined;
    ApiResultLicenseStatus.attributeTypeMap = [
        {
            "name": "status",
            "baseName": "status",
            "type": "LicenseStatus"
        }
    ];
    return ApiResultLicenseStatus;
}());
exports.ApiResultLicenseStatus = ApiResultLicenseStatus;
