/**
 * Pyramid Analytics Web API
 * Pyramid Analytics Web API enables user applications to manage their pyramid                                             data and settings
 *
 * The version of the OpenAPI document: 2023.12.181
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { TaskStatus } from './taskStatus';

/**
* An object containing the task status
*/
export class ApiResultTaskStatus {
    'status'?: TaskStatus;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "status",
            "baseName": "status",
            "type": "TaskStatus"
        }    ];

    static getAttributeTypeMap() {
        return ApiResultTaskStatus.attributeTypeMap;
    }
}

