"use strict";
/**
 * Pyramid Analytics Web API
 * Pyramid Analytics Web API enables user applications to manage their pyramid                                             data and settings
 *
 * The version of the OpenAPI document: 2023.12.181
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.AxisTotalsType = void 0;
/**
* The type of totals column/row
*/
var AxisTotalsType;
(function (AxisTotalsType) {
    AxisTotalsType[AxisTotalsType["None"] = 'NONE'] = "None";
    AxisTotalsType[AxisTotalsType["GrandTotal"] = 'GRAND_TOTAL'] = "GrandTotal";
    AxisTotalsType[AxisTotalsType["GrandAndSubTotal"] = 'GRAND_AND_SUB_TOTAL'] = "GrandAndSubTotal";
    AxisTotalsType[AxisTotalsType["SubTotal"] = 'SUB_TOTAL'] = "SubTotal";
})(AxisTotalsType || (exports.AxisTotalsType = AxisTotalsType = {}));
