/**
 * Pyramid Analytics Web API
 * Pyramid Analytics Web API enables user applications to manage their pyramid                                             data and settings
 *
 * The version of the OpenAPI document: 2023.12.181
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* The type of totals column/row
*/
export enum AxisTotalsType {
    None = <any> 'NONE',
    GrandTotal = <any> 'GRAND_TOTAL',
    GrandAndSubTotal = <any> 'GRAND_AND_SUB_TOTAL',
    SubTotal = <any> 'SUB_TOTAL'
}
