"use strict";
/**
 * Pyramid Analytics Web API
 * Pyramid Analytics Web API enables user applications to manage their pyramid                                             data and settings
 *
 * The version of the OpenAPI document: 2023.12.181
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.BulkWritingType = void 0;
/**
* Describes the write type for Synapse
*/
var BulkWritingType;
(function (BulkWritingType) {
    BulkWritingType[BulkWritingType["None"] = 'NONE'] = "None";
    BulkWritingType[BulkWritingType["SqlBulkCopy"] = 'SQL_BULK_COPY'] = "SqlBulkCopy";
    BulkWritingType[BulkWritingType["CopyFromStorage"] = 'COPY_FROM_STORAGE'] = "CopyFromStorage";
})(BulkWritingType || (exports.BulkWritingType = BulkWritingType = {}));
