"use strict";
/**
 * Pyramid Analytics Web API
 * Pyramid Analytics Web API enables user applications to manage their pyramid                                             data and settings
 *
 * The version of the OpenAPI document: 2023.12.181
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.CartesianVisual = void 0;
/**
* Settings for the Cartesian visual
*/
var CartesianVisual = /** @class */ (function () {
    function CartesianVisual() {
        /**
        * Value used to determine the type of the item receiving, use the class name
        */
        this['inheritanceType'] = 'CartesianVisual';
    }
    CartesianVisual.getAttributeTypeMap = function () {
        return CartesianVisual.attributeTypeMap;
    };
    CartesianVisual.discriminator = undefined;
    CartesianVisual.attributeTypeMap = [
        {
            "name": "filter",
            "baseName": "filter",
            "type": "CartesianFilterDropZone"
        },
        {
            "name": "visualType",
            "baseName": "visualType",
            "type": "CartesianVisualType"
        },
        {
            "name": "trellisHorizontal",
            "baseName": "trellisHorizontal",
            "type": "CartesianTrellisHorizontalDropZone"
        },
        {
            "name": "color",
            "baseName": "color",
            "type": "CartesianColorDropZone"
        },
        {
            "name": "size",
            "baseName": "size",
            "type": "CartesianSizeDropZone"
        },
        {
            "name": "motion",
            "baseName": "motion",
            "type": "CartesianMotionDropZone"
        },
        {
            "name": "shape",
            "baseName": "shape",
            "type": "CartesianShapeDropZone"
        },
        {
            "name": "trellisVertical",
            "baseName": "trellisVertical",
            "type": "CartesianTrellisVerticalDropZone"
        },
        {
            "name": "values",
            "baseName": "values",
            "type": "CartesianValuesDropZone"
        },
        {
            "name": "tooltip",
            "baseName": "tooltip",
            "type": "CartesianTooltipDropZone"
        },
        {
            "name": "categories",
            "baseName": "categories",
            "type": "CartesianCategoriesDropZone"
        },
        {
            "name": "labels",
            "baseName": "labels",
            "type": "CartesianLabelsDropZone"
        },
        {
            "name": "inheritanceType",
            "baseName": "inheritanceType",
            "type": "string"
        }
    ];
    return CartesianVisual;
}());
exports.CartesianVisual = CartesianVisual;
