/**
 * Pyramid Analytics Web API
 * Pyramid Analytics Web API enables user applications to manage their pyramid                                             data and settings
 *
 * The version of the OpenAPI document: 2023.12.181
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { CartesianBarVisualType } from './cartesianBarVisualType';
import { CartesianColumnVisualType } from './cartesianColumnVisualType';
import { CartesianLineVisualType } from './cartesianLineVisualType';
import { CartesianStackedBarVisualType } from './cartesianStackedBarVisualType';
import { CartesianStackedColumnVisualType } from './cartesianStackedColumnVisualType';

/**
* Settings for the Values measure drop zone chip for the Cartesian visual
*/
export class CartesianValuesVisualTypes {
    'barVisualType'?: CartesianBarVisualType;
    'stackedBarVisualType'?: CartesianStackedBarVisualType;
    'lineVisualType'?: CartesianLineVisualType;
    'stackedColumnVisualType'?: CartesianStackedColumnVisualType;
    'columnVisualType'?: CartesianColumnVisualType;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "barVisualType",
            "baseName": "barVisualType",
            "type": "CartesianBarVisualType"
        },
        {
            "name": "stackedBarVisualType",
            "baseName": "stackedBarVisualType",
            "type": "CartesianStackedBarVisualType"
        },
        {
            "name": "lineVisualType",
            "baseName": "lineVisualType",
            "type": "CartesianLineVisualType"
        },
        {
            "name": "stackedColumnVisualType",
            "baseName": "stackedColumnVisualType",
            "type": "CartesianStackedColumnVisualType"
        },
        {
            "name": "columnVisualType",
            "baseName": "columnVisualType",
            "type": "CartesianColumnVisualType"
        }    ];

    static getAttributeTypeMap() {
        return CartesianValuesVisualTypes.attributeTypeMap;
    }
}

