"use strict";
/**
 * Pyramid Analytics Web API
 * Pyramid Analytics Web API enables user applications to manage their pyramid                                             data and settings
 *
 * The version of the OpenAPI document: 2023.12.181
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.CartesianTrellisHorizontalChip = void 0;
/**
* Settings for the TrellisHorizontal drop zone chip for the Cartesian visual
*/
var CartesianTrellisHorizontalChip = /** @class */ (function () {
    function CartesianTrellisHorizontalChip() {
        /**
        * Value used to determine the type of the item receiving, use the class name
        */
        this['inheritanceType'] = 'CartesianTrellisHorizontalChip';
    }
    CartesianTrellisHorizontalChip.getAttributeTypeMap = function () {
        return CartesianTrellisHorizontalChip.attributeTypeMap;
    };
    CartesianTrellisHorizontalChip.discriminator = undefined;
    CartesianTrellisHorizontalChip.attributeTypeMap = [
        {
            "name": "values",
            "baseName": "values",
            "type": "CartesianTrellisHorizontalValuesChip"
        },
        {
            "name": "hierarchy",
            "baseName": "hierarchy",
            "type": "CartesianTrellisHorizontalHierarchyChip"
        },
        {
            "name": "inheritanceType",
            "baseName": "inheritanceType",
            "type": "string"
        }
    ];
    return CartesianTrellisHorizontalChip;
}());
exports.CartesianTrellisHorizontalChip = CartesianTrellisHorizontalChip;
