"use strict";
/**
 * Pyramid Analytics Web API
 * Pyramid Analytics Web API enables user applications to manage their pyramid                                             data and settings
 *
 * The version of the OpenAPI document: 2023.12.181
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.CartesianLineVisualType = void 0;
/**
* The type of graphical chart or visualization used as the primary or secondary axis of the line charts
*/
var CartesianLineVisualType;
(function (CartesianLineVisualType) {
    CartesianLineVisualType[CartesianLineVisualType["ColumnChart"] = 'ColumnChart'] = "ColumnChart";
    CartesianLineVisualType[CartesianLineVisualType["LineChart"] = 'LineChart'] = "LineChart";
    CartesianLineVisualType[CartesianLineVisualType["SplineChart"] = 'SplineChart'] = "SplineChart";
    CartesianLineVisualType[CartesianLineVisualType["StepLineChart"] = 'StepLineChart'] = "StepLineChart";
    CartesianLineVisualType[CartesianLineVisualType["PointChart"] = 'PointChart'] = "PointChart";
    CartesianLineVisualType[CartesianLineVisualType["LollipopChart"] = 'LollipopChart'] = "LollipopChart";
    CartesianLineVisualType[CartesianLineVisualType["AreaChart"] = 'AreaChart'] = "AreaChart";
    CartesianLineVisualType[CartesianLineVisualType["SplineAreaChart"] = 'SplineAreaChart'] = "SplineAreaChart";
    CartesianLineVisualType[CartesianLineVisualType["StepLineAreaChart"] = 'StepLineAreaChart'] = "StepLineAreaChart";
    CartesianLineVisualType[CartesianLineVisualType["StackedAreaChart"] = 'StackedAreaChart'] = "StackedAreaChart";
    CartesianLineVisualType[CartesianLineVisualType["SplineStackedAreaChart"] = 'SplineStackedAreaChart'] = "SplineStackedAreaChart";
    CartesianLineVisualType[CartesianLineVisualType["StepLineStackedAreaChart"] = 'StepLineStackedAreaChart'] = "StepLineStackedAreaChart";
    CartesianLineVisualType[CartesianLineVisualType["Stacked100AreaChart"] = 'Stacked100AreaChart'] = "Stacked100AreaChart";
    CartesianLineVisualType[CartesianLineVisualType["SplineStacked100AreaChart"] = 'SplineStacked100AreaChart'] = "SplineStacked100AreaChart";
    CartesianLineVisualType[CartesianLineVisualType["StepLineStacked100AreaChart"] = 'StepLineStacked100AreaChart'] = "StepLineStacked100AreaChart";
    CartesianLineVisualType[CartesianLineVisualType["StreamAreaChart"] = 'StreamAreaChart'] = "StreamAreaChart";
    CartesianLineVisualType[CartesianLineVisualType["StreamSplineChart"] = 'StreamSplineChart'] = "StreamSplineChart";
    CartesianLineVisualType[CartesianLineVisualType["StreamStepChart"] = 'StreamStepChart'] = "StreamStepChart";
})(CartesianLineVisualType || (exports.CartesianLineVisualType = CartesianLineVisualType = {}));
