"use strict";
/**
 * Pyramid Analytics Web API
 * Pyramid Analytics Web API enables user applications to manage their pyramid                                             data and settings
 *
 * The version of the OpenAPI document: 2023.12.181
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.CartesianFilterHierarchyChip = void 0;
/**
* Settings for the Filter hierarchy drop zone chip for the Cartesian visual
*/
var CartesianFilterHierarchyChip = /** @class */ (function () {
    function CartesianFilterHierarchyChip() {
        /**
        * Value used to determine the type of the item receiving, use the class name
        */
        this['inheritanceType'] = 'CartesianFilterHierarchyChip';
    }
    CartesianFilterHierarchyChip.getAttributeTypeMap = function () {
        return CartesianFilterHierarchyChip.attributeTypeMap;
    };
    CartesianFilterHierarchyChip.discriminator = undefined;
    CartesianFilterHierarchyChip.attributeTypeMap = [
        {
            "name": "uniqueName",
            "baseName": "uniqueName",
            "type": "string"
        },
        {
            "name": "filterType",
            "baseName": "filterType",
            "type": "FilterHierarchyType"
        },
        {
            "name": "inheritanceType",
            "baseName": "inheritanceType",
            "type": "string"
        }
    ];
    return CartesianFilterHierarchyChip;
}());
exports.CartesianFilterHierarchyChip = CartesianFilterHierarchyChip;
