"use strict";
/**
 * Pyramid Analytics Web API
 * Pyramid Analytics Web API enables user applications to manage their pyramid                                             data and settings
 *
 * The version of the OpenAPI document: 2023.12.181
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.CartesianShapeDropZone = void 0;
/**
* Settings for the Shape drop zone for the Cartesian visual
*/
var CartesianShapeDropZone = /** @class */ (function () {
    function CartesianShapeDropZone() {
        /**
        * Value used to determine the type of the item receiving, use the class name
        */
        this['inheritanceType'] = 'CartesianShapeDropZone';
    }
    CartesianShapeDropZone.getAttributeTypeMap = function () {
        return CartesianShapeDropZone.attributeTypeMap;
    };
    CartesianShapeDropZone.discriminator = undefined;
    CartesianShapeDropZone.attributeTypeMap = [
        {
            "name": "dropZoneChips",
            "baseName": "dropZoneChips",
            "type": "Array<CartesianShapeChip>"
        },
        {
            "name": "inheritanceType",
            "baseName": "inheritanceType",
            "type": "string"
        }
    ];
    return CartesianShapeDropZone;
}());
exports.CartesianShapeDropZone = CartesianShapeDropZone;
