"use strict";
/**
 * Pyramid Analytics Web API
 * Pyramid Analytics Web API enables user applications to manage their pyramid                                             data and settings
 *
 * The version of the OpenAPI document: 2023.12.181
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.CartesianColumnVisualType = void 0;
/**
* The type of graphical chart or visualization used as the primary or secondary axis of the column charts
*/
var CartesianColumnVisualType;
(function (CartesianColumnVisualType) {
    CartesianColumnVisualType[CartesianColumnVisualType["ColumnChart"] = 'ColumnChart'] = "ColumnChart";
    CartesianColumnVisualType[CartesianColumnVisualType["LineChart"] = 'LineChart'] = "LineChart";
    CartesianColumnVisualType[CartesianColumnVisualType["SplineChart"] = 'SplineChart'] = "SplineChart";
    CartesianColumnVisualType[CartesianColumnVisualType["StepLineChart"] = 'StepLineChart'] = "StepLineChart";
    CartesianColumnVisualType[CartesianColumnVisualType["PointChart"] = 'PointChart'] = "PointChart";
    CartesianColumnVisualType[CartesianColumnVisualType["LollipopChart"] = 'LollipopChart'] = "LollipopChart";
    CartesianColumnVisualType[CartesianColumnVisualType["AreaChart"] = 'AreaChart'] = "AreaChart";
    CartesianColumnVisualType[CartesianColumnVisualType["SplineAreaChart"] = 'SplineAreaChart'] = "SplineAreaChart";
    CartesianColumnVisualType[CartesianColumnVisualType["StepLineAreaChart"] = 'StepLineAreaChart'] = "StepLineAreaChart";
    CartesianColumnVisualType[CartesianColumnVisualType["StackedAreaChart"] = 'StackedAreaChart'] = "StackedAreaChart";
    CartesianColumnVisualType[CartesianColumnVisualType["SplineStackedAreaChart"] = 'SplineStackedAreaChart'] = "SplineStackedAreaChart";
    CartesianColumnVisualType[CartesianColumnVisualType["StepLineStackedAreaChart"] = 'StepLineStackedAreaChart'] = "StepLineStackedAreaChart";
    CartesianColumnVisualType[CartesianColumnVisualType["Stacked100AreaChart"] = 'Stacked100AreaChart'] = "Stacked100AreaChart";
    CartesianColumnVisualType[CartesianColumnVisualType["SplineStacked100AreaChart"] = 'SplineStacked100AreaChart'] = "SplineStacked100AreaChart";
    CartesianColumnVisualType[CartesianColumnVisualType["StepLineStacked100AreaChart"] = 'StepLineStacked100AreaChart'] = "StepLineStacked100AreaChart";
    CartesianColumnVisualType[CartesianColumnVisualType["StreamAreaChart"] = 'StreamAreaChart'] = "StreamAreaChart";
    CartesianColumnVisualType[CartesianColumnVisualType["StreamSplineChart"] = 'StreamSplineChart'] = "StreamSplineChart";
    CartesianColumnVisualType[CartesianColumnVisualType["StreamStepChart"] = 'StreamStepChart'] = "StreamStepChart";
})(CartesianColumnVisualType || (exports.CartesianColumnVisualType = CartesianColumnVisualType = {}));
