"use strict";
/**
 * Pyramid Analytics Web API
 * Pyramid Analytics Web API enables user applications to manage their pyramid                                             data and settings
 *
 * The version of the OpenAPI document: 2023.12.181
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.CartesianSizeMeasureChip = void 0;
/**
* Settings for the Size measure drop zone chip for the Cartesian visual
*/
var CartesianSizeMeasureChip = /** @class */ (function () {
    function CartesianSizeMeasureChip() {
        /**
        * Value used to determine the type of the item receiving, use the class name
        */
        this['inheritanceType'] = 'CartesianSizeMeasureChip';
    }
    CartesianSizeMeasureChip.getAttributeTypeMap = function () {
        return CartesianSizeMeasureChip.attributeTypeMap;
    };
    CartesianSizeMeasureChip.discriminator = undefined;
    CartesianSizeMeasureChip.attributeTypeMap = [
        {
            "name": "uniqueName",
            "baseName": "uniqueName",
            "type": "string"
        },
        {
            "name": "sizeMathFunction",
            "baseName": "sizeMathFunction",
            "type": "SizeMathFunction"
        },
        {
            "name": "inheritanceType",
            "baseName": "inheritanceType",
            "type": "string"
        }
    ];
    return CartesianSizeMeasureChip;
}());
exports.CartesianSizeMeasureChip = CartesianSizeMeasureChip;
