"use strict";
/**
 * Pyramid Analytics Web API
 * Pyramid Analytics Web API enables user applications to manage their pyramid                                             data and settings
 *
 * The version of the OpenAPI document: 2023.12.181
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.CartesianStackedColumnVisualType = void 0;
/**
* The type of graphical chart or visualization used as the primary or secondary axis of the stacked column charts
*/
var CartesianStackedColumnVisualType;
(function (CartesianStackedColumnVisualType) {
    CartesianStackedColumnVisualType[CartesianStackedColumnVisualType["StackedColumnChart"] = 'StackedColumnChart'] = "StackedColumnChart";
    CartesianStackedColumnVisualType[CartesianStackedColumnVisualType["Stacked100ColumnChart"] = 'Stacked100ColumnChart'] = "Stacked100ColumnChart";
    CartesianStackedColumnVisualType[CartesianStackedColumnVisualType["SplineChart"] = 'SplineChart'] = "SplineChart";
    CartesianStackedColumnVisualType[CartesianStackedColumnVisualType["StepLineChart"] = 'StepLineChart'] = "StepLineChart";
    CartesianStackedColumnVisualType[CartesianStackedColumnVisualType["PointChart"] = 'PointChart'] = "PointChart";
    CartesianStackedColumnVisualType[CartesianStackedColumnVisualType["LollipopChart"] = 'LollipopChart'] = "LollipopChart";
    CartesianStackedColumnVisualType[CartesianStackedColumnVisualType["AreaChart"] = 'AreaChart'] = "AreaChart";
    CartesianStackedColumnVisualType[CartesianStackedColumnVisualType["SplineAreaChart"] = 'SplineAreaChart'] = "SplineAreaChart";
    CartesianStackedColumnVisualType[CartesianStackedColumnVisualType["StepLineAreaChart"] = 'StepLineAreaChart'] = "StepLineAreaChart";
    CartesianStackedColumnVisualType[CartesianStackedColumnVisualType["StackedAreaChart"] = 'StackedAreaChart'] = "StackedAreaChart";
    CartesianStackedColumnVisualType[CartesianStackedColumnVisualType["SplineStackedAreaChart"] = 'SplineStackedAreaChart'] = "SplineStackedAreaChart";
    CartesianStackedColumnVisualType[CartesianStackedColumnVisualType["StepLineStackedAreaChart"] = 'StepLineStackedAreaChart'] = "StepLineStackedAreaChart";
    CartesianStackedColumnVisualType[CartesianStackedColumnVisualType["Stacked100AreaChart"] = 'Stacked100AreaChart'] = "Stacked100AreaChart";
    CartesianStackedColumnVisualType[CartesianStackedColumnVisualType["SplineStacked100AreaChart"] = 'SplineStacked100AreaChart'] = "SplineStacked100AreaChart";
    CartesianStackedColumnVisualType[CartesianStackedColumnVisualType["StepLineStacked100AreaChart"] = 'StepLineStacked100AreaChart'] = "StepLineStacked100AreaChart";
    CartesianStackedColumnVisualType[CartesianStackedColumnVisualType["StreamAreaChart"] = 'StreamAreaChart'] = "StreamAreaChart";
    CartesianStackedColumnVisualType[CartesianStackedColumnVisualType["StreamSplineChart"] = 'StreamSplineChart'] = "StreamSplineChart";
    CartesianStackedColumnVisualType[CartesianStackedColumnVisualType["StreamStepChart"] = 'StreamStepChart'] = "StreamStepChart";
})(CartesianStackedColumnVisualType || (exports.CartesianStackedColumnVisualType = CartesianStackedColumnVisualType = {}));
