"use strict";
/**
 * Pyramid Analytics Web API
 * Pyramid Analytics Web API enables user applications to manage their pyramid                                             data and settings
 *
 * The version of the OpenAPI document: 2023.12.181
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ChangeUserLicenseObject = void 0;
/**
* The change license type object contains the license settings for a given user.
*/
var ChangeUserLicenseObject = /** @class */ (function () {
    function ChangeUserLicenseObject() {
    }
    ChangeUserLicenseObject.getAttributeTypeMap = function () {
        return ChangeUserLicenseObject.attributeTypeMap;
    };
    ChangeUserLicenseObject.discriminator = undefined;
    ChangeUserLicenseObject.attributeTypeMap = [
        {
            "name": "licenseType",
            "baseName": "licenseType",
            "type": "ClientLicenseType"
        },
        {
            "name": "userId",
            "baseName": "userId",
            "type": "string"
        }
    ];
    return ChangeUserLicenseObject;
}());
exports.ChangeUserLicenseObject = ChangeUserLicenseObject;
