"use strict";
/**
 * Pyramid Analytics Web API
 * Pyramid Analytics Web API enables user applications to manage their pyramid                                             data and settings
 *
 * The version of the OpenAPI document: 2023.12.181
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ClashDefaultOption = void 0;
/**
* Clash default option is the operation neededed to be taken when items of the same name are encountered.
*/
var ClashDefaultOption;
(function (ClashDefaultOption) {
    ClashDefaultOption[ClashDefaultOption["RegularPieImport"] = 'REGULAR_PIE_IMPORT'] = "RegularPieImport";
    ClashDefaultOption[ClashDefaultOption["ReplaceFile"] = 'REPLACE_FILE'] = "ReplaceFile";
    ClashDefaultOption[ClashDefaultOption["AddNew"] = 'ADD_NEW'] = "AddNew";
    ClashDefaultOption[ClashDefaultOption["Skip"] = 'SKIP'] = "Skip";
})(ClashDefaultOption || (exports.ClashDefaultOption = ClashDefaultOption = {}));
