/**
 * Pyramid Analytics Web API
 * Pyramid Analytics Web API enables user applications to manage their pyramid                                             data and settings
 *
 * The version of the OpenAPI document: 2023.12.181
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* The user license type enumeration.
*/
export enum ClientLicenseType {
    Scientist = <any> 'Scientist',
    Professional = <any> 'Professional',
    Analyst = <any> 'Analyst',
    Viewer = <any> 'Viewer',
    Basic = <any> 'Basic',
    None = <any> 'None'
}
