/**
 * Pyramid Analytics Web API
 * Pyramid Analytics Web API enables user applications to manage their pyramid                                             data and settings
 *
 * The version of the OpenAPI document: 2023.12.181
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* The connection object representing the details of the data sources
*/
export class ConnectionStringData {
    /**
    * Indicating if this is a dynamic loaded model, should be true in case of a model that Is loaded on demand like MS OLAP, SAP BW, etc..
    */
    'dynamicModel'?: boolean;
    /**
    * The data source server\'s display name
    */
    'serverName'?: string;
    /**
    * The name of the model (existing OLAP cube, tabular model or view)
    */
    'model'?: string;
    /**
    * The name of the database
    */
    'dataBaseName'?: string;
    /**
    * The data source server\'s ID
    */
    'serverId'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "dynamicModel",
            "baseName": "dynamicModel",
            "type": "boolean"
        },
        {
            "name": "serverName",
            "baseName": "serverName",
            "type": "string"
        },
        {
            "name": "model",
            "baseName": "model",
            "type": "string"
        },
        {
            "name": "dataBaseName",
            "baseName": "dataBaseName",
            "type": "string"
        },
        {
            "name": "serverId",
            "baseName": "serverId",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ConnectionStringData.attributeTypeMap;
    }
}

