/**
 * Pyramid Analytics Web API
 * Pyramid Analytics Web API enables user applications to manage their pyramid                                             data and settings
 *
 * The version of the OpenAPI document: 2023.12.181
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ConnectionStringType } from './connectionStringType';

/**
* The connection object representing the details of the data sources.
*/
export class ConnectionStringProperties {
    /**
    * The model\'s name
    */
    'modelName'?: string;
    /**
    * Boolean showing if a model is dynamic
    */
    'isDynamicModel'?: boolean;
    /**
    * The materialized model\'s system ID
    */
    'modelId'?: string;
    /**
    * The data source server\'s name
    */
    'serverName'?: string;
    /**
    * The data source  database\'s system ID
    */
    'dataBaseId'?: string;
    'connectionStringType'?: ConnectionStringType;
    /**
    * The connection object\'s system ID
    */
    'id'?: string;
    /**
    * The data source database\'s name
    */
    'dataBaseName'?: string;
    /**
    * Last process of the model. 
    */
    'modelProcessDate'?: Date;
    /**
    * The data source  server\'s system ID
    */
    'serverId'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "modelName",
            "baseName": "modelName",
            "type": "string"
        },
        {
            "name": "isDynamicModel",
            "baseName": "isDynamicModel",
            "type": "boolean"
        },
        {
            "name": "modelId",
            "baseName": "modelId",
            "type": "string"
        },
        {
            "name": "serverName",
            "baseName": "serverName",
            "type": "string"
        },
        {
            "name": "dataBaseId",
            "baseName": "dataBaseId",
            "type": "string"
        },
        {
            "name": "connectionStringType",
            "baseName": "connectionStringType",
            "type": "ConnectionStringType"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "dataBaseName",
            "baseName": "dataBaseName",
            "type": "string"
        },
        {
            "name": "modelProcessDate",
            "baseName": "modelProcessDate",
            "type": "Date"
        },
        {
            "name": "serverId",
            "baseName": "serverId",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ConnectionStringProperties.attributeTypeMap;
    }
}

