"use strict";
/**
 * Pyramid Analytics Web API
 * Pyramid Analytics Web API enables user applications to manage their pyramid                                             data and settings
 *
 * The version of the OpenAPI document: 2023.12.181
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ConnectedItemsSearchCriteria = void 0;
/**
* The search criteria for finding materialized data elements.
*/
var ConnectedItemsSearchCriteria = /** @class */ (function () {
    function ConnectedItemsSearchCriteria() {
    }
    ConnectedItemsSearchCriteria.getAttributeTypeMap = function () {
        return ConnectedItemsSearchCriteria.attributeTypeMap;
    };
    ConnectedItemsSearchCriteria.discriminator = undefined;
    ConnectedItemsSearchCriteria.attributeTypeMap = [
        {
            "name": "dataContainerId",
            "baseName": "dataContainerId",
            "type": "string"
        },
        {
            "name": "searchCriteria",
            "baseName": "searchCriteria",
            "type": "SearchCriteria"
        }
    ];
    return ConnectedItemsSearchCriteria;
}());
exports.ConnectedItemsSearchCriteria = ConnectedItemsSearchCriteria;
