"use strict";
/**
 * Pyramid Analytics Web API
 * Pyramid Analytics Web API enables user applications to manage their pyramid                                             data and settings
 *
 * The version of the OpenAPI document: 2023.12.181
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ConnectionStringData = void 0;
/**
* The connection object representing the details of the data sources
*/
var ConnectionStringData = /** @class */ (function () {
    function ConnectionStringData() {
    }
    ConnectionStringData.getAttributeTypeMap = function () {
        return ConnectionStringData.attributeTypeMap;
    };
    ConnectionStringData.discriminator = undefined;
    ConnectionStringData.attributeTypeMap = [
        {
            "name": "dynamicModel",
            "baseName": "dynamicModel",
            "type": "boolean"
        },
        {
            "name": "serverName",
            "baseName": "serverName",
            "type": "string"
        },
        {
            "name": "model",
            "baseName": "model",
            "type": "string"
        },
        {
            "name": "dataBaseName",
            "baseName": "dataBaseName",
            "type": "string"
        },
        {
            "name": "serverId",
            "baseName": "serverId",
            "type": "string"
        }
    ];
    return ConnectionStringData;
}());
exports.ConnectionStringData = ConnectionStringData;
