/**
 * Pyramid Analytics Web API
 * Pyramid Analytics Web API enables user applications to manage their pyramid                                             data and settings
 *
 * The version of the OpenAPI document: 2023.12.181
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* The item content type
*/
export enum ContentType {
    None = <any> 'None',
    Illustrate = <any> 'Illustrate',
    Formulation = <any> 'Formulation',
    Discover = <any> 'Discover',
    Model = <any> 'Model',
    Folder = <any> 'Folder',
    Publication = <any> 'Publication',
    Server = <any> 'Server',
    Presentation = <any> 'Presentation',
    Document = <any> 'Document',
    Component = <any> 'Component',
    Theme = <any> 'Theme',
    Prom = <any> 'Prom',
    ContentView = <any> 'ContentView',
    KpiBandsContainer = <any> 'KpiBandsContainer',
    DataSource = <any> 'DataSource',
    Tabulation = <any> 'Tabulation',
    SolveArea = <any> 'SolveArea',
    StagedMlModel = <any> 'StagedMLModel'
}
