/**
 * Pyramid Analytics Web API
 * Pyramid Analytics Web API enables user applications to manage their pyramid                                             data and settings
 *
 * The version of the OpenAPI document: 2023.12.181
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Content type enumeration.
*/
export enum ContentTypeObject {
    None = <any> 'None',
    Asset = <any> 'Asset',
    Calculation = <any> 'Calculation',
    DataDiscovery = <any> 'DataDiscovery',
    EtlFlow = <any> 'ETLFlow',
    Folder = <any> 'Folder',
    Publisher = <any> 'Publisher',
    Storyboard = <any> 'Storyboard'
}
