"use strict";
/**
 * Pyramid Analytics Web API
 * Pyramid Analytics Web API enables user applications to manage their pyramid                                             data and settings
 *
 * The version of the OpenAPI document: 2023.12.181
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ContentSearchParamsObject = void 0;
/**
* The content search object for specifying search criteria to be used in content searches.
*/
var ContentSearchParamsObject = /** @class */ (function () {
    function ContentSearchParamsObject() {
    }
    ContentSearchParamsObject.getAttributeTypeMap = function () {
        return ContentSearchParamsObject.attributeTypeMap;
    };
    ContentSearchParamsObject.discriminator = undefined;
    ContentSearchParamsObject.attributeTypeMap = [
        {
            "name": "server",
            "baseName": "server",
            "type": "string"
        },
        {
            "name": "dataBase",
            "baseName": "dataBase",
            "type": "string"
        },
        {
            "name": "folderPathToSearch",
            "baseName": "folderPathToSearch",
            "type": "string"
        },
        {
            "name": "isAdvancedSearch",
            "baseName": "isAdvancedSearch",
            "type": "boolean"
        },
        {
            "name": "searchRootFolderType",
            "baseName": "searchRootFolderType",
            "type": "SearchRootFolderType"
        },
        {
            "name": "startModifiedDate",
            "baseName": "startModifiedDate",
            "type": "Date"
        },
        {
            "name": "searchString",
            "baseName": "searchString",
            "type": "string"
        },
        {
            "name": "searchMatchType",
            "baseName": "searchMatchType",
            "type": "SearchMatchType"
        },
        {
            "name": "endModifiedDate",
            "baseName": "endModifiedDate",
            "type": "Date"
        },
        {
            "name": "startCreatedDate",
            "baseName": "startCreatedDate",
            "type": "Date"
        },
        {
            "name": "model",
            "baseName": "model",
            "type": "string"
        },
        {
            "name": "endCreatedDate",
            "baseName": "endCreatedDate",
            "type": "Date"
        },
        {
            "name": "filterTypes",
            "baseName": "filterTypes",
            "type": "Array<ContentTypeObject>"
        },
        {
            "name": "allowFallback",
            "baseName": "allowFallback",
            "type": "boolean"
        }
    ];
    return ContentSearchParamsObject;
}());
exports.ContentSearchParamsObject = ContentSearchParamsObject;
