"use strict";
/**
 * Pyramid Analytics Web API
 * Pyramid Analytics Web API enables user applications to manage their pyramid                                             data and settings
 *
 * The version of the OpenAPI document: 2023.12.181
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ContentType = void 0;
/**
* The item content type
*/
var ContentType;
(function (ContentType) {
    ContentType[ContentType["None"] = 'None'] = "None";
    ContentType[ContentType["Illustrate"] = 'Illustrate'] = "Illustrate";
    ContentType[ContentType["Formulation"] = 'Formulation'] = "Formulation";
    ContentType[ContentType["Discover"] = 'Discover'] = "Discover";
    ContentType[ContentType["Model"] = 'Model'] = "Model";
    ContentType[ContentType["Folder"] = 'Folder'] = "Folder";
    ContentType[ContentType["Publication"] = 'Publication'] = "Publication";
    ContentType[ContentType["Server"] = 'Server'] = "Server";
    ContentType[ContentType["Presentation"] = 'Presentation'] = "Presentation";
    ContentType[ContentType["Document"] = 'Document'] = "Document";
    ContentType[ContentType["Component"] = 'Component'] = "Component";
    ContentType[ContentType["Theme"] = 'Theme'] = "Theme";
    ContentType[ContentType["Prom"] = 'Prom'] = "Prom";
    ContentType[ContentType["ContentView"] = 'ContentView'] = "ContentView";
    ContentType[ContentType["KpiBandsContainer"] = 'KpiBandsContainer'] = "KpiBandsContainer";
    ContentType[ContentType["DataSource"] = 'DataSource'] = "DataSource";
    ContentType[ContentType["Tabulation"] = 'Tabulation'] = "Tabulation";
    ContentType[ContentType["SolveArea"] = 'SolveArea'] = "SolveArea";
    ContentType[ContentType["StagedMlModel"] = 'StagedMLModel'] = "StagedMlModel";
})(ContentType || (exports.ContentType = ContentType = {}));
