/**
 * Pyramid Analytics Web API
 * Pyramid Analytics Web API enables user applications to manage their pyramid                                             data and settings
 *
 * The version of the OpenAPI document: 2023.12.181
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { AdminType } from './adminType';
import { ClientLicenseType } from './clientLicenseType';
import { LanguageType } from './languageType';
import { UserProfileType } from './userProfileType';
import { UserStatusID } from './userStatusID';

/**
* The object used to create a new user when AD authentication is used.
*/
export class CreateUserAdObject {
    /**
    * The domain net bios
    */
    'adDomainName': string;
    /**
    * The user\'s list of roles
    */
    'roleIds'?: Set<string>;
    'adminType'?: AdminType;
    'statusID'?: UserStatusID;
    'profileType'?: UserProfileType;
    /**
    * The profile ID to be applied for this user
    */
    'profileId'?: string;
    /**
    * The user\'s tenant ID
    */
    'tenantId'?: string;
    'clientLicenseType': ClientLicenseType;
    'language'?: LanguageType;
    /**
    * The user\'s system ID.
    */
    'id'?: string;
    /**
    * The login username for the user
    */
    'userName': string;
    /**
    * The user\'s second proxy account needed for connecting to different data sources
    */
    'proxy2'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "adDomainName",
            "baseName": "adDomainName",
            "type": "string"
        },
        {
            "name": "roleIds",
            "baseName": "roleIds",
            "type": "Set<string>"
        },
        {
            "name": "adminType",
            "baseName": "adminType",
            "type": "AdminType"
        },
        {
            "name": "statusID",
            "baseName": "statusID",
            "type": "UserStatusID"
        },
        {
            "name": "profileType",
            "baseName": "profileType",
            "type": "UserProfileType"
        },
        {
            "name": "profileId",
            "baseName": "profileId",
            "type": "string"
        },
        {
            "name": "tenantId",
            "baseName": "tenantId",
            "type": "string"
        },
        {
            "name": "clientLicenseType",
            "baseName": "clientLicenseType",
            "type": "ClientLicenseType"
        },
        {
            "name": "language",
            "baseName": "language",
            "type": "LanguageType"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "userName",
            "baseName": "userName",
            "type": "string"
        },
        {
            "name": "proxy2",
            "baseName": "proxy2",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return CreateUserAdObject.attributeTypeMap;
    }
}

