/**
 * Pyramid Analytics Web API
 * Pyramid Analytics Web API enables user applications to manage their pyramid                                             data and settings
 *
 * The version of the OpenAPI document: 2023.12.181
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Determines which type of end-user authentication to use when connecting to destination server
*/
export enum CubeAuthMethod {
    EffectiveUserName = <any> 'EffectiveUserName',
    CustomData = <any> 'CustomData',
    None = <any> 'None'
}
