/**
 * Pyramid Analytics Web API
 * Pyramid Analytics Web API enables user applications to manage their pyramid                                             data and settings
 *
 * The version of the OpenAPI document: 2023.12.181
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Defines options to use as a custom Root Certificate Authority for the trust validation of SSL certificates
*/
export enum CustomRootCAType {
    None = <any> 'None',
    CustomRootCaCert = <any> 'CustomRootCaCert',
    CustomTrustStore = <any> 'CustomTrustStore'
}
