/**
 * Pyramid Analytics Web API
 * Pyramid Analytics Web API enables user applications to manage their pyramid                                             data and settings
 *
 * The version of the OpenAPI document: 2023.12.181
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* The type of data
*/
export enum DataType {
    Integer = <any> 'Integer',
    Decimal = <any> 'Decimal',
    Float = <any> 'Float',
    Currency = <any> 'Currency',
    Date = <any> 'Date',
    DateTime = <any> 'DateTime',
    Time = <any> 'Time',
    Boolean = <any> 'Boolean',
    String = <any> 'String',
    Image = <any> 'Image',
    BigInteger = <any> 'BigInteger',
    Unsupported = <any> 'Unsupported',
    Uuid = <any> 'UUID',
    Object = <any> 'Object',
    Double = <any> 'Double',
    NString = <any> 'NString'
}
