/**
 * Pyramid Analytics Web API
 * Pyramid Analytics Web API enables user applications to manage their pyramid                                             data and settings
 *
 * The version of the OpenAPI document: 2023.12.181
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { AggregationType } from './aggregationType';

/**
* Describes a Measure in the model
*/
export class DataCatalogMeasure {
    /**
    * The unique name of the Measure, as used in Formulate
    */
    'uniqueName'?: string;
    /**
    * The format of the Measure
    */
    'format'?: string;
    /**
    * The description of the Measure
    */
    'description'?: string;
    'aggregation'?: AggregationType;
    /**
    * The name of the Measure
    */
    'measureName'?: string;
    /**
    * Used to associate dimensions with measures
    */
    'group'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "uniqueName",
            "baseName": "uniqueName",
            "type": "string"
        },
        {
            "name": "format",
            "baseName": "format",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "aggregation",
            "baseName": "aggregation",
            "type": "AggregationType"
        },
        {
            "name": "measureName",
            "baseName": "measureName",
            "type": "string"
        },
        {
            "name": "group",
            "baseName": "group",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return DataCatalogMeasure.attributeTypeMap;
    }
}

