"use strict";
/**
 * Pyramid Analytics Web API
 * Pyramid Analytics Web API enables user applications to manage their pyramid                                             data and settings
 *
 * The version of the OpenAPI document: 2023.12.181
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.DataCatalogUpdateData = void 0;
/**
* Data for data catalog update operation
*/
var DataCatalogUpdateData = /** @class */ (function () {
    function DataCatalogUpdateData() {
    }
    DataCatalogUpdateData.getAttributeTypeMap = function () {
        return DataCatalogUpdateData.attributeTypeMap;
    };
    DataCatalogUpdateData.discriminator = undefined;
    DataCatalogUpdateData.attributeTypeMap = [
        {
            "name": "materializedModelId",
            "baseName": "materializedModelId",
            "type": "string"
        },
        {
            "name": "dataCatalog",
            "baseName": "dataCatalog",
            "type": "ModelDataCatalog"
        }
    ];
    return DataCatalogUpdateData;
}());
exports.DataCatalogUpdateData = DataCatalogUpdateData;
