"use strict";
/**
 * Pyramid Analytics Web API
 * Pyramid Analytics Web API enables user applications to manage their pyramid                                             data and settings
 *
 * The version of the OpenAPI document: 2023.12.181
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.DataType = void 0;
/**
* The type of data
*/
var DataType;
(function (DataType) {
    DataType[DataType["Integer"] = 'Integer'] = "Integer";
    DataType[DataType["Decimal"] = 'Decimal'] = "Decimal";
    DataType[DataType["Float"] = 'Float'] = "Float";
    DataType[DataType["Currency"] = 'Currency'] = "Currency";
    DataType[DataType["Date"] = 'Date'] = "Date";
    DataType[DataType["DateTime"] = 'DateTime'] = "DateTime";
    DataType[DataType["Time"] = 'Time'] = "Time";
    DataType[DataType["Boolean"] = 'Boolean'] = "Boolean";
    DataType[DataType["String"] = 'String'] = "String";
    DataType[DataType["Image"] = 'Image'] = "Image";
    DataType[DataType["BigInteger"] = 'BigInteger'] = "BigInteger";
    DataType[DataType["Unsupported"] = 'Unsupported'] = "Unsupported";
    DataType[DataType["Uuid"] = 'UUID'] = "Uuid";
    DataType[DataType["Object"] = 'Object'] = "Object";
    DataType[DataType["Double"] = 'Double'] = "Double";
    DataType[DataType["NString"] = 'NString'] = "NString";
})(DataType || (exports.DataType = DataType = {}));
