"use strict";
/**
 * Pyramid Analytics Web API
 * Pyramid Analytics Web API enables user applications to manage their pyramid                                             data and settings
 *
 * The version of the OpenAPI document: 2023.12.181
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.DataCatalogModelMetadata = void 0;
/**
* Describes the metadata of the discover object
*/
var DataCatalogModelMetadata = /** @class */ (function () {
    function DataCatalogModelMetadata() {
    }
    DataCatalogModelMetadata.getAttributeTypeMap = function () {
        return DataCatalogModelMetadata.attributeTypeMap;
    };
    DataCatalogModelMetadata.discriminator = undefined;
    DataCatalogModelMetadata.attributeTypeMap = [
        {
            "name": "modelName",
            "baseName": "modelName",
            "type": "string"
        },
        {
            "name": "createdDate",
            "baseName": "createdDate",
            "type": "Date"
        },
        {
            "name": "createdBy",
            "baseName": "createdBy",
            "type": "string"
        },
        {
            "name": "datasource",
            "baseName": "datasource",
            "type": "string"
        },
        {
            "name": "serverType",
            "baseName": "serverType",
            "type": "ConnectionStringType"
        },
        {
            "name": "modifiedDate",
            "baseName": "modifiedDate",
            "type": "Date"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "modifiedBy",
            "baseName": "modifiedBy",
            "type": "string"
        },
        {
            "name": "dimensionCount",
            "baseName": "dimensionCount",
            "type": "number"
        },
        {
            "name": "measureCount",
            "baseName": "measureCount",
            "type": "number"
        },
        {
            "name": "lastProcessDate",
            "baseName": "lastProcessDate",
            "type": "Date"
        }
    ];
    return DataCatalogModelMetadata;
}());
exports.DataCatalogModelMetadata = DataCatalogModelMetadata;
