"use strict";
/**
 * Pyramid Analytics Web API
 * Pyramid Analytics Web API enables user applications to manage their pyramid                                             data and settings
 *
 * The version of the OpenAPI document: 2023.12.181
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.DiscoverDataCatalog = void 0;
/**
* Describes the discover model
*/
var DiscoverDataCatalog = /** @class */ (function () {
    function DiscoverDataCatalog() {
    }
    DiscoverDataCatalog.getAttributeTypeMap = function () {
        return DiscoverDataCatalog.attributeTypeMap;
    };
    DiscoverDataCatalog.discriminator = undefined;
    DiscoverDataCatalog.attributeTypeMap = [
        {
            "name": "metadata",
            "baseName": "metadata",
            "type": "DataCatalogModelMetadata"
        },
        {
            "name": "measures",
            "baseName": "measures",
            "type": "Array<DataCatalogMeasure>"
        },
        {
            "name": "dimensions",
            "baseName": "dimensions",
            "type": "Array<DataCatalogDimension>"
        }
    ];
    return DiscoverDataCatalog;
}());
exports.DiscoverDataCatalog = DiscoverDataCatalog;
