"use strict";
/**
 * Pyramid Analytics Web API
 * Pyramid Analytics Web API enables user applications to manage their pyramid                                             data and settings
 *
 * The version of the OpenAPI document: 2023.12.181
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.DistributionType = void 0;
var DistributionType;
(function (DistributionType) {
    DistributionType[DistributionType["Email"] = 'Email'] = "Email";
    DistributionType[DistributionType["Portal"] = 'Portal'] = "Portal";
    DistributionType[DistributionType["PhoneMessaging"] = 'PhoneMessaging'] = "PhoneMessaging";
    DistributionType[DistributionType["Webhook"] = 'Webhook'] = "Webhook";
})(DistributionType || (exports.DistributionType = DistributionType = {}));
