"use strict";
/**
 * Pyramid Analytics Web API
 * Pyramid Analytics Web API enables user applications to manage their pyramid                                             data and settings
 *
 * The version of the OpenAPI document: 2023.12.181
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.DomainAdminPermissions = void 0;
/**
* The functional items to be available in the profile as either a list or a sum index bits. The list will take priority if both are supplied
*/
var DomainAdminPermissions = /** @class */ (function () {
    function DomainAdminPermissions() {
    }
    DomainAdminPermissions.getAttributeTypeMap = function () {
        return DomainAdminPermissions.attributeTypeMap;
    };
    DomainAdminPermissions.discriminator = undefined;
    DomainAdminPermissions.attributeTypeMap = [
        {
            "name": "permissionBitIndexList",
            "baseName": "permissionBitIndexList",
            "type": "Array<DomainAdminPermissionType>"
        },
        {
            "name": "numeric",
            "baseName": "numeric",
            "type": "number"
        }
    ];
    return DomainAdminPermissions;
}());
exports.DomainAdminPermissions = DomainAdminPermissions;
