/**
 * Pyramid Analytics Web API
 * Pyramid Analytics Web API enables user applications to manage their pyramid                                             data and settings
 *
 * The version of the OpenAPI document: 2023.12.181
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Domain Admin permission types.
*/
export enum DomainAdminPermissionType {
    Access = <any> 'Access',
    Data = <any> 'Data',
    Content = <any> 'Content',
    Schedules = <any> 'Schedules',
    Logs = <any> 'Logs',
    Mobile = <any> 'Mobile',
    Design = <any> 'Design',
    Geospatial = <any> 'Geospatial',
    AiDsAndMl = <any> 'AiDsAndMl'
}
