"use strict";
/**
 * Pyramid Analytics Web API
 * Pyramid Analytics Web API enables user applications to manage their pyramid                                             data and settings
 *
 * The version of the OpenAPI document: 2023.12.181
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.DscApiData = void 0;
/**
* The data source changer settings object.
*/
var DscApiData = /** @class */ (function () {
    function DscApiData() {
    }
    DscApiData.getAttributeTypeMap = function () {
        return DscApiData.attributeTypeMap;
    };
    DscApiData.discriminator = undefined;
    DscApiData.attributeTypeMap = [
        {
            "name": "itemId",
            "baseName": "itemId",
            "type": "string"
        },
        {
            "name": "toConnId",
            "baseName": "toConnId",
            "type": "string"
        },
        {
            "name": "fromConnId",
            "baseName": "fromConnId",
            "type": "string"
        }
    ];
    return DscApiData;
}());
exports.DscApiData = DscApiData;
