"use strict";
/**
 * Pyramid Analytics Web API
 * Pyramid Analytics Web API enables user applications to manage their pyramid                                             data and settings
 *
 * The version of the OpenAPI document: 2023.12.181
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ElementSelectionData = void 0;
/**
* Describes single selection in hierarchy
*/
var ElementSelectionData = /** @class */ (function () {
    function ElementSelectionData() {
    }
    ElementSelectionData.getAttributeTypeMap = function () {
        return ElementSelectionData.attributeTypeMap;
    };
    ElementSelectionData.discriminator = undefined;
    ElementSelectionData.attributeTypeMap = [
        {
            "name": "selectionType",
            "baseName": "selectionType",
            "type": "ElementSelectionDataType"
        },
        {
            "name": "uniqueNames",
            "baseName": "UniqueNames",
            "type": "Array<string>"
        }
    ];
    return ElementSelectionData;
}());
exports.ElementSelectionData = ElementSelectionData;
