/**
 * Pyramid Analytics Web API
 * Pyramid Analytics Web API enables user applications to manage their pyramid                                             data and settings
 *
 * The version of the OpenAPI document: 2023.12.181
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ErrorMessage } from './errorMessage';
import { MasterNodeError } from './masterNodeError';
import { TaskSummary } from './taskSummary';

export class EtlTaskSummary extends TaskSummary {
    'taskSuccess'?: boolean;
    'taskValidationErrors'?: Array<MasterNodeError>;
    /**
    * Value used to determine the type of the item receiving, use the class name
    */
    'inheritanceType'?: string = 'EtlTaskSummary';

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "taskSuccess",
            "baseName": "taskSuccess",
            "type": "boolean"
        },
        {
            "name": "taskValidationErrors",
            "baseName": "taskValidationErrors",
            "type": "Array<MasterNodeError>"
        },
        {
            "name": "inheritanceType",
            "baseName": "inheritanceType",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(EtlTaskSummary.attributeTypeMap);
    }
}

