"use strict";
/**
 * Pyramid Analytics Web API
 * Pyramid Analytics Web API enables user applications to manage their pyramid                                             data and settings
 *
 * The version of the OpenAPI document: 2023.12.181
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ExecuteScheduleApiData = void 0;
/**
* An object for settings the execution parameters of a schedule.
*/
var ExecuteScheduleApiData = /** @class */ (function () {
    function ExecuteScheduleApiData() {
    }
    ExecuteScheduleApiData.getAttributeTypeMap = function () {
        return ExecuteScheduleApiData.attributeTypeMap;
    };
    ExecuteScheduleApiData.discriminator = undefined;
    ExecuteScheduleApiData.attributeTypeMap = [
        {
            "name": "checkTriggers",
            "baseName": "checkTriggers",
            "type": "boolean"
        },
        {
            "name": "scheduleId",
            "baseName": "scheduleId",
            "type": "string"
        }
    ];
    return ExecuteScheduleApiData;
}());
exports.ExecuteScheduleApiData = ExecuteScheduleApiData;
