"use strict";
/**
 * Pyramid Analytics Web API
 * Pyramid Analytics Web API enables user applications to manage their pyramid                                             data and settings
 *
 * The version of the OpenAPI document: 2023.12.181
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ExecutionViewData = void 0;
/**
* The execution object contains all the details of scheduled execution instance.
*/
var ExecutionViewData = /** @class */ (function () {
    function ExecutionViewData() {
    }
    ExecutionViewData.getAttributeTypeMap = function () {
        return ExecutionViewData.attributeTypeMap;
    };
    ExecutionViewData.discriminator = undefined;
    ExecutionViewData.attributeTypeMap = [
        {
            "name": "endDate",
            "baseName": "endDate",
            "type": "Date"
        },
        {
            "name": "outputType",
            "baseName": "outputType",
            "type": "PrintingOutputType"
        },
        {
            "name": "failedPct",
            "baseName": "failedPct",
            "type": "number"
        },
        {
            "name": "error",
            "baseName": "error",
            "type": "string"
        },
        {
            "name": "partialSuccessCount",
            "baseName": "partialSuccessCount",
            "type": "number"
        },
        {
            "name": "failedCount",
            "baseName": "failedCount",
            "type": "number"
        },
        {
            "name": "triggerStoppedPct",
            "baseName": "triggerStoppedPct",
            "type": "number"
        },
        {
            "name": "partialSuccessPct",
            "baseName": "partialSuccessPct",
            "type": "number"
        },
        {
            "name": "canceledCount",
            "baseName": "canceledCount",
            "type": "number"
        },
        {
            "name": "pendingCount",
            "baseName": "pendingCount",
            "type": "number"
        },
        {
            "name": "runningPct",
            "baseName": "runningPct",
            "type": "number"
        },
        {
            "name": "pendingPct",
            "baseName": "pendingPct",
            "type": "number"
        },
        {
            "name": "triggerStoppedCount",
            "baseName": "triggerStoppedCount",
            "type": "number"
        },
        {
            "name": "canceledPct",
            "baseName": "canceledPct",
            "type": "number"
        },
        {
            "name": "runningCount",
            "baseName": "runningCount",
            "type": "number"
        },
        {
            "name": "successCount",
            "baseName": "successCount",
            "type": "number"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "successPct",
            "baseName": "successPct",
            "type": "number"
        },
        {
            "name": "items",
            "baseName": "items",
            "type": "Array<TaskViewData>"
        },
        {
            "name": "startDate",
            "baseName": "startDate",
            "type": "Date"
        }
    ];
    return ExecutionViewData;
}());
exports.ExecutionViewData = ExecutionViewData;
