"use strict";
/**
 * Pyramid Analytics Web API
 * Pyramid Analytics Web API enables user applications to manage their pyramid                                             data and settings
 *
 * The version of the OpenAPI document: 2023.12.181
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ExportData = void 0;
/**
* The object representing the exported PIE file.
*/
var ExportData = /** @class */ (function () {
    function ExportData() {
    }
    ExportData.getAttributeTypeMap = function () {
        return ExportData.attributeTypeMap;
    };
    ExportData.discriminator = undefined;
    ExportData.attributeTypeMap = [
        {
            "name": "fileName",
            "baseName": "fileName",
            "type": "string"
        },
        {
            "name": "fileData",
            "baseName": "fileData",
            "type": "string"
        }
    ];
    return ExportData;
}());
exports.ExportData = ExportData;
