"use strict";
/**
 * Pyramid Analytics Web API
 * Pyramid Analytics Web API enables user applications to manage their pyramid                                             data and settings
 *
 * The version of the OpenAPI document: 2023.12.181
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ExternalParameters = void 0;
/**
* The parameter object used to specify filters and targets to be used to parameterize the query in the export.
*/
var ExternalParameters = /** @class */ (function () {
    function ExternalParameters() {
    }
    ExternalParameters.getAttributeTypeMap = function () {
        return ExternalParameters.attributeTypeMap;
    };
    ExternalParameters.discriminator = undefined;
    ExternalParameters.attributeTypeMap = [
        {
            "name": "reportFilters",
            "baseName": "reportFilters",
            "type": "Array<FilterParameter>"
        },
        {
            "name": "slideNumber",
            "baseName": "slideNumber",
            "type": "number"
        },
        {
            "name": "targets",
            "baseName": "targets",
            "type": "Array<TargetParameter>"
        }
    ];
    return ExternalParameters;
}());
exports.ExternalParameters = ExternalParameters;
