"use strict";
/**
 * Pyramid Analytics Web API
 * Pyramid Analytics Web API enables user applications to manage their pyramid                                             data and settings
 *
 * The version of the OpenAPI document: 2023.12.181
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.FilterHierarchyType = void 0;
/**
* The type of filter for hierarchy chip
*/
var FilterHierarchyType;
(function (FilterHierarchyType) {
    FilterHierarchyType[FilterHierarchyType["DropDownSingleSelect"] = 'DropDownSingleSelect'] = "DropDownSingleSelect";
    FilterHierarchyType[FilterHierarchyType["DropDownMultiSelect"] = 'DropDownMultiSelect'] = "DropDownMultiSelect";
    FilterHierarchyType[FilterHierarchyType["ListBox"] = 'ListBox'] = "ListBox";
    FilterHierarchyType[FilterHierarchyType["MultiSelectListBox"] = 'MultiSelectListBox'] = "MultiSelectListBox";
    FilterHierarchyType[FilterHierarchyType["Tree"] = 'Tree'] = "Tree";
    FilterHierarchyType[FilterHierarchyType["CombinedElements"] = 'CombinedElements'] = "CombinedElements";
    FilterHierarchyType[FilterHierarchyType["SingleSelectButtons"] = 'SingleSelectButtons'] = "SingleSelectButtons";
    FilterHierarchyType[FilterHierarchyType["MultiSelectButtons"] = 'MultiSelectButtons'] = "MultiSelectButtons";
    FilterHierarchyType[FilterHierarchyType["TextBox"] = 'TextBox'] = "TextBox";
    FilterHierarchyType[FilterHierarchyType["SingleSelectTree"] = 'SingleSelectTree'] = "SingleSelectTree";
})(FilterHierarchyType || (exports.FilterHierarchyType = FilterHierarchyType = {}));
