/**
 * Pyramid Analytics Web API
 * Pyramid Analytics Web API enables user applications to manage their pyramid                                             data and settings
 *
 * The version of the OpenAPI document: 2023.12.181
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* The type of filter for hierarchy chip
*/
export enum FilterHierarchyType {
    DropDownSingleSelect = <any> 'DropDownSingleSelect',
    DropDownMultiSelect = <any> 'DropDownMultiSelect',
    ListBox = <any> 'ListBox',
    MultiSelectListBox = <any> 'MultiSelectListBox',
    Tree = <any> 'Tree',
    CombinedElements = <any> 'CombinedElements',
    SingleSelectButtons = <any> 'SingleSelectButtons',
    MultiSelectButtons = <any> 'MultiSelectButtons',
    TextBox = <any> 'TextBox',
    SingleSelectTree = <any> 'SingleSelectTree'
}
