"use strict";
/**
 * Pyramid Analytics Web API
 * Pyramid Analytics Web API enables user applications to manage their pyramid                                             data and settings
 *
 * The version of the OpenAPI document: 2023.12.181
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.FtpDataMode = void 0;
/**
* FTP transfer mode - active or passive
*/
var FtpDataMode;
(function (FtpDataMode) {
    FtpDataMode[FtpDataMode["NotSet"] = 'NOT_SET'] = "NotSet";
    FtpDataMode[FtpDataMode["LocalActive"] = 'LOCAL_ACTIVE'] = "LocalActive";
    FtpDataMode[FtpDataMode["LocalPassive"] = 'LOCAL_PASSIVE'] = "LocalPassive";
})(FtpDataMode || (exports.FtpDataMode = FtpDataMode = {}));
