/**
 * Pyramid Analytics Web API
 * Pyramid Analytics Web API enables user applications to manage their pyramid                                             data and settings
 *
 * The version of the OpenAPI document: 2023.12.181
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { FtpDataMode } from './ftpDataMode';
import { FtpSecurityType } from './ftpSecurityType';

/**
* Settings for FTP server connections
*/
export class FtpSettings {
    /**
    * Does the server require reuse TLS connections
    */
    'isRequireReuseTLS'?: boolean;
    /**
    * Minimum value for port range for active FTP
    */
    'portRangeMin'?: number;
    'ftpSecurityType'?: FtpSecurityType;
    /**
    * Maximum value for port range for active FTP
    */
    'portRangeMax'?: number;
    'ftpDataMode'?: FtpDataMode;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "isRequireReuseTLS",
            "baseName": "isRequireReuseTLS",
            "type": "boolean"
        },
        {
            "name": "portRangeMin",
            "baseName": "portRangeMin",
            "type": "number"
        },
        {
            "name": "ftpSecurityType",
            "baseName": "ftpSecurityType",
            "type": "FtpSecurityType"
        },
        {
            "name": "portRangeMax",
            "baseName": "portRangeMax",
            "type": "number"
        },
        {
            "name": "ftpDataMode",
            "baseName": "ftpDataMode",
            "type": "FtpDataMode"
        }    ];

    static getAttributeTypeMap() {
        return FtpSettings.attributeTypeMap;
    }
}

