"use strict";
/**
 * Pyramid Analytics Web API
 * Pyramid Analytics Web API enables user applications to manage their pyramid                                             data and settings
 *
 * The version of the OpenAPI document: 2023.12.181
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.GridColorChip = void 0;
/**
* Settings for the Color drop zone chip for the Grid visual
*/
var GridColorChip = /** @class */ (function () {
    function GridColorChip() {
        /**
        * Value used to determine the type of the item receiving, use the class name
        */
        this['inheritanceType'] = 'GridColorChip';
    }
    GridColorChip.getAttributeTypeMap = function () {
        return GridColorChip.attributeTypeMap;
    };
    GridColorChip.discriminator = undefined;
    GridColorChip.attributeTypeMap = [
        {
            "name": "measure",
            "baseName": "measure",
            "type": "GridColorMeasureChip"
        },
        {
            "name": "hierarchy",
            "baseName": "hierarchy",
            "type": "GridColorHierarchyChip"
        },
        {
            "name": "inheritanceType",
            "baseName": "inheritanceType",
            "type": "string"
        }
    ];
    return GridColorChip;
}());
exports.GridColorChip = GridColorChip;
