"use strict";
/**
 * Pyramid Analytics Web API
 * Pyramid Analytics Web API enables user applications to manage their pyramid                                             data and settings
 *
 * The version of the OpenAPI document: 2023.12.181
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.GridFilterHierarchyChip = void 0;
/**
* Settings for the Filter hierarchy drop zone chip for the Grid visual
*/
var GridFilterHierarchyChip = /** @class */ (function () {
    function GridFilterHierarchyChip() {
        /**
        * Value used to determine the type of the item receiving, use the class name
        */
        this['inheritanceType'] = 'GridFilterHierarchyChip';
    }
    GridFilterHierarchyChip.getAttributeTypeMap = function () {
        return GridFilterHierarchyChip.attributeTypeMap;
    };
    GridFilterHierarchyChip.discriminator = undefined;
    GridFilterHierarchyChip.attributeTypeMap = [
        {
            "name": "uniqueName",
            "baseName": "uniqueName",
            "type": "string"
        },
        {
            "name": "filterType",
            "baseName": "filterType",
            "type": "FilterHierarchyType"
        },
        {
            "name": "inheritanceType",
            "baseName": "inheritanceType",
            "type": "string"
        }
    ];
    return GridFilterHierarchyChip;
}());
exports.GridFilterHierarchyChip = GridFilterHierarchyChip;
