"use strict";
/**
 * Pyramid Analytics Web API
 * Pyramid Analytics Web API enables user applications to manage their pyramid                                             data and settings
 *
 * The version of the OpenAPI document: 2023.12.181
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.GridRowsChip = void 0;
/**
* Settings for the Rows drop zone chip for the Grid visual
*/
var GridRowsChip = /** @class */ (function () {
    function GridRowsChip() {
        /**
        * Value used to determine the type of the item receiving, use the class name
        */
        this['inheritanceType'] = 'GridRowsChip';
    }
    GridRowsChip.getAttributeTypeMap = function () {
        return GridRowsChip.attributeTypeMap;
    };
    GridRowsChip.discriminator = undefined;
    GridRowsChip.attributeTypeMap = [
        {
            "name": "values",
            "baseName": "values",
            "type": "GridRowsValuesChip"
        },
        {
            "name": "hierarchy",
            "baseName": "hierarchy",
            "type": "GridRowsHierarchyChip"
        },
        {
            "name": "inheritanceType",
            "baseName": "inheritanceType",
            "type": "string"
        }
    ];
    return GridRowsChip;
}());
exports.GridRowsChip = GridRowsChip;
