"use strict";
/**
 * Pyramid Analytics Web API
 * Pyramid Analytics Web API enables user applications to manage their pyramid                                             data and settings
 *
 * The version of the OpenAPI document: 2023.12.181
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.HierarchyCategory = void 0;
/**
* Predefined categories for hierarchies (none/date/geo location/person)
*/
var HierarchyCategory;
(function (HierarchyCategory) {
    HierarchyCategory[HierarchyCategory["None"] = 'NONE'] = "None";
    HierarchyCategory[HierarchyCategory["Date"] = 'DATE'] = "Date";
    HierarchyCategory[HierarchyCategory["GeoLocation"] = 'GeoLocation'] = "GeoLocation";
    HierarchyCategory[HierarchyCategory["Person"] = 'PERSON'] = "Person";
})(HierarchyCategory || (exports.HierarchyCategory = HierarchyCategory = {}));
