/**
 * Pyramid Analytics Web API
 * Pyramid Analytics Web API enables user applications to manage their pyramid                                             data and settings
 *
 * The version of the OpenAPI document: 2023.12.181
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Details of the security settings to be applied to a data model\'s hierarchies or measures.
*/
export class HierarchyMeasureSecurity {
    /**
    * The unique names of the items, in a list. Use hierarchies for hierarchy security, use measures for measures security
    */
    'uniqueNames': Array<string>;
    /**
    * The model\'s ID
    */
    'modelId': string;
    /**
    * The role id the settings apply to
    */
    'roleId': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "uniqueNames",
            "baseName": "uniqueNames",
            "type": "Array<string>"
        },
        {
            "name": "modelId",
            "baseName": "modelId",
            "type": "string"
        },
        {
            "name": "roleId",
            "baseName": "roleId",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return HierarchyMeasureSecurity.attributeTypeMap;
    }
}

