"use strict";
/**
 * Pyramid Analytics Web API
 * Pyramid Analytics Web API enables user applications to manage their pyramid                                             data and settings
 *
 * The version of the OpenAPI document: 2023.12.181
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.IsolationMode = void 0;
/**
* See https://learn.microsoft.com/en-us/sql/mdx/mdx-data-definition-create-member?view=sql-server-ver16#scope for details
*/
var IsolationMode;
(function (IsolationMode) {
    IsolationMode[IsolationMode["Cube"] = 'Cube'] = "Cube";
    IsolationMode[IsolationMode["None"] = 'None'] = "None";
})(IsolationMode || (exports.IsolationMode = IsolationMode = {}));
