/**
 * Pyramid Analytics Web API
 * Pyramid Analytics Web API enables user applications to manage their pyramid                                             data and settings
 *
 * The version of the OpenAPI document: 2023.12.181
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* The move items object with details of the selected content items and the destination folder.
*/
export class ItemsToMove {
    /**
    * The destination folder ID
    */
    'destinationFolder': string;
    /**
    * List of content item ID\'s
    */
    'itemsForMove': Array<string>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "destinationFolder",
            "baseName": "destinationFolder",
            "type": "string"
        },
        {
            "name": "itemsForMove",
            "baseName": "itemsForMove",
            "type": "Array<string>"
        }    ];

    static getAttributeTypeMap() {
        return ItemsToMove.attributeTypeMap;
    }
}

