"use strict";
/**
 * Pyramid Analytics Web API
 * Pyramid Analytics Web API enables user applications to manage their pyramid                                             data and settings
 *
 * The version of the OpenAPI document: 2023.12.181
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ItemRolePair = void 0;
/**
* Object with role and role access types.
*/
var ItemRolePair = /** @class */ (function () {
    function ItemRolePair() {
    }
    ItemRolePair.getAttributeTypeMap = function () {
        return ItemRolePair.attributeTypeMap;
    };
    ItemRolePair.discriminator = undefined;
    ItemRolePair.attributeTypeMap = [
        {
            "name": "accessType",
            "baseName": "accessType",
            "type": "AccessType"
        },
        {
            "name": "roleId",
            "baseName": "roleId",
            "type": "string"
        }
    ];
    return ItemRolePair;
}());
exports.ItemRolePair = ItemRolePair;
