"use strict";
/**
 * Pyramid Analytics Web API
 * Pyramid Analytics Web API enables user applications to manage their pyramid                                             data and settings
 *
 * The version of the OpenAPI document: 2023.12.181
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ItemParentApiData = void 0;
/**
* The item-parent object used to set the content item\'s parent item ID.
*/
var ItemParentApiData = /** @class */ (function () {
    function ItemParentApiData() {
    }
    ItemParentApiData.getAttributeTypeMap = function () {
        return ItemParentApiData.attributeTypeMap;
    };
    ItemParentApiData.discriminator = undefined;
    ItemParentApiData.attributeTypeMap = [
        {
            "name": "itemId",
            "baseName": "itemId",
            "type": "string"
        },
        {
            "name": "parentId",
            "baseName": "parentId",
            "type": "string"
        }
    ];
    return ItemParentApiData;
}());
exports.ItemParentApiData = ItemParentApiData;
