/**
 * Pyramid Analytics Web API
 * Pyramid Analytics Web API enables user applications to manage their pyramid                                             data and settings
 *
 * The version of the OpenAPI document: 2023.12.181
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* The type of join used in relationships of a data model (inner, right outer, left outer, full outer, or cross join)
*/
export enum JoinType {
    Inner = <any> 'INNER',
    Right = <any> 'RIGHT',
    Left = <any> 'LEFT',
    Full = <any> 'FULL',
    Cross = <any> 'CROSS'
}
