/**
 * Pyramid Analytics Web API
 * Pyramid Analytics Web API enables user applications to manage their pyramid                                             data and settings
 *
 * The version of the OpenAPI document: 2023.12.181
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* The user language enumeration.
*/
export enum LanguageType {
    Hebrew = <any> 'Hebrew',
    English = <any> 'English',
    French = <any> 'French',
    German = <any> 'German',
    Dutch = <any> 'Dutch',
    Spanish = <any> 'Spanish',
    Japanese = <any> 'Japanese',
    Arabic = <any> 'Arabic',
    Italian = <any> 'Italian',
    Portuguese = <any> 'Portuguese',
    Russian = <any> 'Russian',
    Chinese = <any> 'Chinese',
    Turkish = <any> 'Turkish',
    NumbersSystem = <any> 'NumbersSystem'
}
