"use strict";
/**
 * Pyramid Analytics Web API
 * Pyramid Analytics Web API enables user applications to manage their pyramid                                             data and settings
 *
 * The version of the OpenAPI document: 2023.12.181
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.LdapUserObject = void 0;
/**
* The LDAP user object contains a list of all Active Directory users.
*/
var LdapUserObject = /** @class */ (function () {
    function LdapUserObject() {
    }
    LdapUserObject.getAttributeTypeMap = function () {
        return LdapUserObject.attributeTypeMap;
    };
    LdapUserObject.discriminator = undefined;
    LdapUserObject.attributeTypeMap = [
        {
            "name": "firstName",
            "baseName": "firstName",
            "type": "string"
        },
        {
            "name": "lastName",
            "baseName": "lastName",
            "type": "string"
        },
        {
            "name": "domain",
            "baseName": "domain",
            "type": "string"
        },
        {
            "name": "principalName",
            "baseName": "principalName",
            "type": "string"
        },
        {
            "name": "userName",
            "baseName": "userName",
            "type": "string"
        }
    ];
    return LdapUserObject;
}());
exports.LdapUserObject = LdapUserObject;
