/**
 * Pyramid Analytics Web API
 * Pyramid Analytics Web API enables user applications to manage their pyramid                                             data and settings
 *
 * The version of the OpenAPI document: 2023.12.181
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* The LDAP group object contains a list of all Active Directory groups.
*/
export class LdapGroupDetails {
    /**
    * The group\'s AD account name
    */
    'samAccountName'?: string;
    /**
    * The group\'s name
    */
    'name': string;
    /**
    * The group\'s AD GUID
    */
    'guid': string;
    /**
    * The group\'s LDAP domain address
    */
    'domainAddress': string;
    /**
    * The group\'s AD SID
    */
    'sid': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "samAccountName",
            "baseName": "samAccountName",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "guid",
            "baseName": "guid",
            "type": "string"
        },
        {
            "name": "domainAddress",
            "baseName": "domainAddress",
            "type": "string"
        },
        {
            "name": "sid",
            "baseName": "sid",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return LdapGroupDetails.attributeTypeMap;
    }
}

