/**
 * Pyramid Analytics Web API
 * Pyramid Analytics Web API enables user applications to manage their pyramid                                             data and settings
 *
 * The version of the OpenAPI document: 2023.12.181
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { LdapSearchType } from './ldapSearchType';

/**
* The LDAP search object that contains the parameters to be used in Active Directory searches.
*/
export class LdapSearchObject {
    'searchType': LdapSearchType;
    /**
    * The AD domain
    */
    'domainNetBios': string;
    /**
    * The search string
    */
    'searchValue': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "searchType",
            "baseName": "searchType",
            "type": "LdapSearchType"
        },
        {
            "name": "domainNetBios",
            "baseName": "domainNetBios",
            "type": "string"
        },
        {
            "name": "searchValue",
            "baseName": "searchValue",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return LdapSearchObject.attributeTypeMap;
    }
}

