/**
 * Pyramid Analytics Web API
 * Pyramid Analytics Web API enables user applications to manage their pyramid                                             data and settings
 *
 * The version of the OpenAPI document: 2023.12.181
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Object which represents the total numbers of Pro and Viewer user licenses
*/
export class LicenseCountObject {
    /**
    * The total number of basic licenses for the tenant
    */
    'totalBasicSeats'?: number;
    /**
    * The total number of scientist licenses for the tenant
    */
    'totalScientistSeats'?: number;
    /**
    * The total number of analyst licenses for the tenant
    */
    'totalAnalystSeats'?: number;
    /**
    * The total number of viewer licenses for the tenant
    */
    'totalViewerSeats'?: number;
    /**
    * The total number of professional licenses for the tenant
    */
    'totalProSeats'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "totalBasicSeats",
            "baseName": "totalBasicSeats",
            "type": "number"
        },
        {
            "name": "totalScientistSeats",
            "baseName": "totalScientistSeats",
            "type": "number"
        },
        {
            "name": "totalAnalystSeats",
            "baseName": "totalAnalystSeats",
            "type": "number"
        },
        {
            "name": "totalViewerSeats",
            "baseName": "totalViewerSeats",
            "type": "number"
        },
        {
            "name": "totalProSeats",
            "baseName": "totalProSeats",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return LicenseCountObject.attributeTypeMap;
    }
}

