/**
 * Pyramid Analytics Web API
 * Pyramid Analytics Web API enables user applications to manage their pyramid                                             data and settings
 *
 * The version of the OpenAPI document: 2023.12.181
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* The Custom List To add.
*/
export class ListData {
    /**
    * The script syntax of the calculation logic.
    */
    'formulaSyntax': string;
    /**
    * The name of the item as it appears in the content system
    */
    'itemName': string;
    /**
    * A description for the item
    */
    'description'?: string;
    /**
    * The ID of the semantic data model that the item is attached to
    */
    'connectionId': string;
    /**
    * The id of the item
    */
    'id'?: string;
    /**
    * The name of the data model dimension that this formulated item will be attached to
    */
    'parentDimension': string;
    /**
    * The name of the data model hierarchy/attribute within the specified dimension, that this formulated item will be attached to. This is not required for \"measures\"
    */
    'parentHierarchy'?: string;
    /**
    * The ID of the folder where this item will be stored
    */
    'folderId': string;
    /**
    * Tags for the item that can be used in content searches
    */
    'tags'?: Array<string>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "formulaSyntax",
            "baseName": "formulaSyntax",
            "type": "string"
        },
        {
            "name": "itemName",
            "baseName": "itemName",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "connectionId",
            "baseName": "connectionId",
            "type": "string"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "parentDimension",
            "baseName": "parentDimension",
            "type": "string"
        },
        {
            "name": "parentHierarchy",
            "baseName": "parentHierarchy",
            "type": "string"
        },
        {
            "name": "folderId",
            "baseName": "folderId",
            "type": "string"
        },
        {
            "name": "tags",
            "baseName": "tags",
            "type": "Array<string>"
        }    ];

    static getAttributeTypeMap() {
        return ListData.attributeTypeMap;
    }
}

