"use strict";
/**
 * Pyramid Analytics Web API
 * Pyramid Analytics Web API enables user applications to manage their pyramid                                             data and settings
 *
 * The version of the OpenAPI document: 2023.12.181
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.MapFilterDropZone = void 0;
/**
* Settings for the Filter drop zone for the Map visual
*/
var MapFilterDropZone = /** @class */ (function () {
    function MapFilterDropZone() {
        /**
        * Value used to determine the type of the item receiving, use the class name
        */
        this['inheritanceType'] = 'MapFilterDropZone';
    }
    MapFilterDropZone.getAttributeTypeMap = function () {
        return MapFilterDropZone.attributeTypeMap;
    };
    MapFilterDropZone.discriminator = undefined;
    MapFilterDropZone.attributeTypeMap = [
        {
            "name": "dropZoneChips",
            "baseName": "dropZoneChips",
            "type": "Array<MapFilterHierarchyChip>"
        },
        {
            "name": "inheritanceType",
            "baseName": "inheritanceType",
            "type": "string"
        }
    ];
    return MapFilterDropZone;
}());
exports.MapFilterDropZone = MapFilterDropZone;
