/**
 * Pyramid Analytics Web API
 * Pyramid Analytics Web API enables user applications to manage their pyramid                                             data and settings
 *
 * The version of the OpenAPI document: 2023.12.181
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { MeasureMapOptions } from './measureMapOptions';

/**
* Settings for the Location measure drop zone chip for the Map visual
*/
export class MapLocationMeasureChip {
    /**
    * The unique name of the measure or value
    */
    'uniqueName': string;
    'mapOptions'?: MeasureMapOptions;
    /**
    * Value used to determine the type of the item receiving, use the class name
    */
    'inheritanceType'?: string = 'MapLocationMeasureChip';

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "uniqueName",
            "baseName": "uniqueName",
            "type": "string"
        },
        {
            "name": "mapOptions",
            "baseName": "mapOptions",
            "type": "MeasureMapOptions"
        },
        {
            "name": "inheritanceType",
            "baseName": "inheritanceType",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return MapLocationMeasureChip.attributeTypeMap;
    }
}

