"use strict";
/**
 * Pyramid Analytics Web API
 * Pyramid Analytics Web API enables user applications to manage their pyramid                                             data and settings
 *
 * The version of the OpenAPI document: 2023.12.181
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.MapSizeMeasureChip = void 0;
/**
* Settings for the Size measure drop zone chip for the Map visual
*/
var MapSizeMeasureChip = /** @class */ (function () {
    function MapSizeMeasureChip() {
        /**
        * Value used to determine the type of the item receiving, use the class name
        */
        this['inheritanceType'] = 'MapSizeMeasureChip';
    }
    MapSizeMeasureChip.getAttributeTypeMap = function () {
        return MapSizeMeasureChip.attributeTypeMap;
    };
    MapSizeMeasureChip.discriminator = undefined;
    MapSizeMeasureChip.attributeTypeMap = [
        {
            "name": "uniqueName",
            "baseName": "uniqueName",
            "type": "string"
        },
        {
            "name": "sizeMathFunction",
            "baseName": "sizeMathFunction",
            "type": "SizeMathFunction"
        },
        {
            "name": "inheritanceType",
            "baseName": "inheritanceType",
            "type": "string"
        }
    ];
    return MapSizeMeasureChip;
}());
exports.MapSizeMeasureChip = MapSizeMeasureChip;
