/**
 * Pyramid Analytics Web API
 * Pyramid Analytics Web API enables user applications to manage their pyramid                                             data and settings
 *
 * The version of the OpenAPI document: 2023.12.181
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { SizeMathFunction } from './sizeMathFunction';

/**
* Settings for the Size measure drop zone chip for the Map visual
*/
export class MapSizeMeasureChip {
    /**
    * The unique name of the measure or value
    */
    'uniqueName': string;
    'sizeMathFunction'?: SizeMathFunction;
    /**
    * Value used to determine the type of the item receiving, use the class name
    */
    'inheritanceType'?: string = 'MapSizeMeasureChip';

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "uniqueName",
            "baseName": "uniqueName",
            "type": "string"
        },
        {
            "name": "sizeMathFunction",
            "baseName": "sizeMathFunction",
            "type": "SizeMathFunction"
        },
        {
            "name": "inheritanceType",
            "baseName": "inheritanceType",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return MapSizeMeasureChip.attributeTypeMap;
    }
}

