/**
 * Pyramid Analytics Web API
 * Pyramid Analytics Web API enables user applications to manage their pyramid                                             data and settings
 *
 * The version of the OpenAPI document: 2023.12.181
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { MasterFlowOtherObject } from './masterFlowOtherObject';
import { MasterFlowSourceObject } from './masterFlowSourceObject';
import { MasterFlowTargetObject } from './masterFlowTargetObject';
import { MasterFlowVariableObject } from './masterFlowVariableObject';

/**
* Validation result, includes list for each validation type object
*/
export class MasterFlowValidationResult {
    /**
    * Validation results for variables objects
    */
    'variables'?: Array<MasterFlowVariableObject>;
    /**
    * Validation results for sources objects
    */
    'sources'?: Array<MasterFlowSourceObject>;
    /**
    * Validation results for targets objects
    */
    'targets'?: Array<MasterFlowTargetObject>;
    /**
    * Validation results for other objects
    */
    'others'?: Array<MasterFlowOtherObject>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "variables",
            "baseName": "variables",
            "type": "Array<MasterFlowVariableObject>"
        },
        {
            "name": "sources",
            "baseName": "sources",
            "type": "Array<MasterFlowSourceObject>"
        },
        {
            "name": "targets",
            "baseName": "targets",
            "type": "Array<MasterFlowTargetObject>"
        },
        {
            "name": "others",
            "baseName": "others",
            "type": "Array<MasterFlowOtherObject>"
        }    ];

    static getAttributeTypeMap() {
        return MasterFlowValidationResult.attributeTypeMap;
    }
}

