/**
 * Pyramid Analytics Web API
 * Pyramid Analytics Web API enables user applications to manage their pyramid                                             data and settings
 *
 * The version of the OpenAPI document: 2023.12.181
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { UpdateSchemaValidation } from './updateSchemaValidation';

/**
* Use this object to update the database schemas used in the data flow.
*/
export class MasterFlowSchemasObject {
    /**
    * The ID depends on the source: For Model files it is the item\'s system ID. For materialized/deployed models it is its materialized model ID.
    */
    'itemId': string;
    /**
    * Current schema name.
    */
    'fromSchema': string;
    /**
    * Data Flow node\'s ID. The ID can be found in the node\'s property pane within the \'description\' card. For materialized/deployed model of direct query, this value can by blank.
    */
    'dataFlowNodeId'?: string;
    'schemaValidation'?: UpdateSchemaValidation;
    /**
    * New schema name.
    */
    'toSchema': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "itemId",
            "baseName": "itemId",
            "type": "string"
        },
        {
            "name": "fromSchema",
            "baseName": "fromSchema",
            "type": "string"
        },
        {
            "name": "dataFlowNodeId",
            "baseName": "dataFlowNodeId",
            "type": "string"
        },
        {
            "name": "schemaValidation",
            "baseName": "schemaValidation",
            "type": "UpdateSchemaValidation"
        },
        {
            "name": "toSchema",
            "baseName": "toSchema",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return MasterFlowSchemasObject.attributeTypeMap;
    }
}

