"use strict";
/**
 * Pyramid Analytics Web API
 * Pyramid Analytics Web API enables user applications to manage their pyramid                                             data and settings
 *
 * The version of the OpenAPI document: 2023.12.181
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.MasterFlowSchemasObject = void 0;
/**
* Use this object to update the database schemas used in the data flow.
*/
var MasterFlowSchemasObject = /** @class */ (function () {
    function MasterFlowSchemasObject() {
    }
    MasterFlowSchemasObject.getAttributeTypeMap = function () {
        return MasterFlowSchemasObject.attributeTypeMap;
    };
    MasterFlowSchemasObject.discriminator = undefined;
    MasterFlowSchemasObject.attributeTypeMap = [
        {
            "name": "itemId",
            "baseName": "itemId",
            "type": "string"
        },
        {
            "name": "fromSchema",
            "baseName": "fromSchema",
            "type": "string"
        },
        {
            "name": "dataFlowNodeId",
            "baseName": "dataFlowNodeId",
            "type": "string"
        },
        {
            "name": "schemaValidation",
            "baseName": "schemaValidation",
            "type": "UpdateSchemaValidation"
        },
        {
            "name": "toSchema",
            "baseName": "toSchema",
            "type": "string"
        }
    ];
    return MasterFlowSchemasObject;
}());
exports.MasterFlowSchemasObject = MasterFlowSchemasObject;
