"use strict";
/**
 * Pyramid Analytics Web API
 * Pyramid Analytics Web API enables user applications to manage their pyramid                                             data and settings
 *
 * The version of the OpenAPI document: 2023.12.181
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.MasterFlowErrorType = void 0;
var MasterFlowErrorType;
(function (MasterFlowErrorType) {
    MasterFlowErrorType[MasterFlowErrorType["Node"] = 'Node'] = "Node";
    MasterFlowErrorType[MasterFlowErrorType["Variable"] = 'Variable'] = "Variable";
})(MasterFlowErrorType || (exports.MasterFlowErrorType = MasterFlowErrorType = {}));
