"use strict";
/**
 * Pyramid Analytics Web API
 * Pyramid Analytics Web API enables user applications to manage their pyramid                                             data and settings
 *
 * The version of the OpenAPI document: 2023.12.181
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.MeasureOverlayToDeleteData = void 0;
/**
* Measure overlay data to delete.
*/
var MeasureOverlayToDeleteData = /** @class */ (function () {
    function MeasureOverlayToDeleteData() {
    }
    MeasureOverlayToDeleteData.getAttributeTypeMap = function () {
        return MeasureOverlayToDeleteData.attributeTypeMap;
    };
    MeasureOverlayToDeleteData.discriminator = undefined;
    MeasureOverlayToDeleteData.attributeTypeMap = [
        {
            "name": "uniqueName",
            "baseName": "uniqueName",
            "type": "string"
        },
        {
            "name": "propertiesToDelete",
            "baseName": "propertiesToDelete",
            "type": "Array<MeasureOverlayProperty>"
        }
    ];
    return MeasureOverlayToDeleteData;
}());
exports.MeasureOverlayToDeleteData = MeasureOverlayToDeleteData;
