/**
 * Pyramid Analytics Web API
 * Pyramid Analytics Web API enables user applications to manage their pyramid                                             data and settings
 *
 * The version of the OpenAPI document: 2023.12.181
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Predefined measure overlay format string
*/
export enum MeasureFormat {
    Option1 = <any> 'Option1',
    Option2 = <any> 'Option2',
    Option3 = <any> 'Option3',
    Option4 = <any> 'Option4',
    Option5 = <any> 'Option5',
    Option6 = <any> 'Option6',
    Option7 = <any> 'Option7',
    Option8 = <any> 'Option8',
    Option9 = <any> 'Option9',
    Option10 = <any> 'Option10',
    Option11 = <any> 'Option11',
    Option12 = <any> 'Option12',
    Option13 = <any> 'Option13',
    Option14 = <any> 'Option14',
    Option15 = <any> 'Option15'
}
