"use strict";
/**
 * Pyramid Analytics Web API
 * Pyramid Analytics Web API enables user applications to manage their pyramid                                             data and settings
 *
 * The version of the OpenAPI document: 2023.12.181
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.MeasureOverlayProperty = void 0;
/**
* Predefined measure overlay properties
*/
var MeasureOverlayProperty;
(function (MeasureOverlayProperty) {
    MeasureOverlayProperty[MeasureOverlayProperty["AlternativeName"] = 'AlternativeName'] = "AlternativeName";
    MeasureOverlayProperty[MeasureOverlayProperty["Format"] = 'Format'] = "Format";
    MeasureOverlayProperty[MeasureOverlayProperty["Description"] = 'Description'] = "Description";
    MeasureOverlayProperty[MeasureOverlayProperty["DisplayFolder"] = 'DisplayFolder'] = "DisplayFolder";
})(MeasureOverlayProperty || (exports.MeasureOverlayProperty = MeasureOverlayProperty = {}));
