"use strict";
/**
 * Pyramid Analytics Web API
 * Pyramid Analytics Web API enables user applications to manage their pyramid                                             data and settings
 *
 * The version of the OpenAPI document: 2023.12.181
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.MeasureMapOptions = void 0;
/**
* The type of geolocation chip
*/
var MeasureMapOptions;
(function (MeasureMapOptions) {
    MeasureMapOptions[MeasureMapOptions["Latitude"] = 'Latitude'] = "Latitude";
    MeasureMapOptions[MeasureMapOptions["Longitude"] = 'Longitude'] = "Longitude";
})(MeasureMapOptions || (exports.MeasureMapOptions = MeasureMapOptions = {}));
