"use strict";
/**
 * Pyramid Analytics Web API
 * Pyramid Analytics Web API enables user applications to manage their pyramid                                             data and settings
 *
 * The version of the OpenAPI document: 2023.12.181
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.MemberDataApi = void 0;
/**
* Describe the information about a single member
*/
var MemberDataApi = /** @class */ (function () {
    function MemberDataApi() {
    }
    MemberDataApi.getAttributeTypeMap = function () {
        return MemberDataApi.attributeTypeMap;
    };
    MemberDataApi.discriminator = undefined;
    MemberDataApi.attributeTypeMap = [
        {
            "name": "uniqueName",
            "baseName": "uniqueName",
            "type": "string"
        },
        {
            "name": "caption",
            "baseName": "caption",
            "type": "string"
        }
    ];
    return MemberDataApi;
}());
exports.MemberDataApi = MemberDataApi;
