"use strict";
/**
 * Pyramid Analytics Web API
 * Pyramid Analytics Web API enables user applications to manage their pyramid                                             data and settings
 *
 * The version of the OpenAPI document: 2023.12.181
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ModelingTableType = void 0;
/**
* Table type: regular database table (identified by schema and table name) or a custom query
*/
var ModelingTableType;
(function (ModelingTableType) {
    ModelingTableType[ModelingTableType["Table"] = 'Table'] = "Table";
    ModelingTableType[ModelingTableType["CustomQueryTable"] = 'CustomQueryTable'] = "CustomQueryTable";
})(ModelingTableType || (exports.ModelingTableType = ModelingTableType = {}));
