"use strict";
/**
 * Pyramid Analytics Web API
 * Pyramid Analytics Web API enables user applications to manage their pyramid                                             data and settings
 *
 * The version of the OpenAPI document: 2023.12.181
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ModelingModel = void 0;
/**
* The model definition that contains details of tables, their relationships and joins, and measures.
*/
var ModelingModel = /** @class */ (function () {
    function ModelingModel() {
    }
    ModelingModel.getAttributeTypeMap = function () {
        return ModelingModel.attributeTypeMap;
    };
    ModelingModel.discriminator = undefined;
    ModelingModel.attributeTypeMap = [
        {
            "name": "defaultDateFormat",
            "baseName": "defaultDateFormat",
            "type": "string"
        },
        {
            "name": "databaseName",
            "baseName": "databaseName",
            "type": "string"
        },
        {
            "name": "modelId",
            "baseName": "modelId",
            "type": "string"
        },
        {
            "name": "defaultMeasureUniqueName",
            "baseName": "defaultMeasureUniqueName",
            "type": "string"
        },
        {
            "name": "displayName",
            "baseName": "displayName",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "modelType",
            "baseName": "modelType",
            "type": "DataFlowModelType"
        },
        {
            "name": "additionalLanguages",
            "baseName": "additionalLanguages",
            "type": "{ [key: string]: string; }"
        },
        {
            "name": "serverId",
            "baseName": "serverId",
            "type": "string"
        },
        {
            "name": "modelingTranslation",
            "baseName": "modelingTranslation",
            "type": "ModelingTranslation"
        },
        {
            "name": "allLevelName",
            "baseName": "allLevelName",
            "type": "string"
        },
        {
            "name": "pchLevelTemplate",
            "baseName": "pchLevelTemplate",
            "type": "string"
        },
        {
            "name": "relationships",
            "baseName": "relationships",
            "type": "Array<ModelingRelationship>"
        },
        {
            "name": "nullMemberCaption",
            "baseName": "nullMemberCaption",
            "type": "string"
        },
        {
            "name": "tables",
            "baseName": "tables",
            "type": "Array<ModelingTable>"
        },
        {
            "name": "serverInfo",
            "baseName": "serverInfo",
            "type": "ModelingServerInfo"
        },
        {
            "name": "arrange",
            "baseName": "arrange",
            "type": "boolean"
        },
        {
            "name": "culture",
            "baseName": "culture",
            "type": "string"
        },
        {
            "name": "modelDataFlowSourceInfo",
            "baseName": "modelDataFlowSourceInfo",
            "type": "ModelDataFlowSourceInfo"
        },
        {
            "name": "allMemberName",
            "baseName": "allMemberName",
            "type": "string"
        },
        {
            "name": "measureGroups",
            "baseName": "measureGroups",
            "type": "Set<MeasureGroup>"
        },
        {
            "name": "syncColumnsSettings",
            "baseName": "syncColumnsSettings",
            "type": "Array<ModelSyncColumnsSettings>"
        },
        {
            "name": "disableCacheMode",
            "baseName": "disableCacheMode",
            "type": "boolean"
        },
        {
            "name": "isAutoIndexing",
            "baseName": "isAutoIndexing",
            "type": "boolean"
        }
    ];
    return ModelingModel;
}());
exports.ModelingModel = ModelingModel;
