"use strict";
/**
 * Pyramid Analytics Web API
 * Pyramid Analytics Web API enables user applications to manage their pyramid                                             data and settings
 *
 * The version of the OpenAPI document: 2023.12.181
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ModelRecognitionObject = void 0;
/**
* The model and its details.
*/
var ModelRecognitionObject = /** @class */ (function () {
    function ModelRecognitionObject() {
    }
    ModelRecognitionObject.getAttributeTypeMap = function () {
        return ModelRecognitionObject.attributeTypeMap;
    };
    ModelRecognitionObject.discriminator = undefined;
    ModelRecognitionObject.attributeTypeMap = [
        {
            "name": "modelName",
            "baseName": "modelName",
            "type": "string"
        },
        {
            "name": "isDynamicModel",
            "baseName": "isDynamicModel",
            "type": "boolean"
        },
        {
            "name": "databaseName",
            "baseName": "databaseName",
            "type": "string"
        },
        {
            "name": "serverId",
            "baseName": "serverId",
            "type": "string"
        }
    ];
    return ModelRecognitionObject;
}());
exports.ModelRecognitionObject = ModelRecognitionObject;
