/**
 * Pyramid Analytics Web API
 * Pyramid Analytics Web API enables user applications to manage their pyramid                                             data and settings
 *
 * The version of the OpenAPI document: 2023.12.181
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Predefined categories for modeling columns
*/
export enum ModelingColumnCategories {
    None = <any> 'None',
    Year = <any> 'Year',
    Quarter = <any> 'Quarter',
    Month = <any> 'Month',
    WeekNumber = <any> 'WeekNumber',
    WeekDay = <any> 'WeekDay',
    DayOfMonth = <any> 'DayOfMonth',
    MonthName = <any> 'MonthName',
    DayName = <any> 'DayName',
    Time = <any> 'Time',
    Date = <any> 'Date',
    DateTime = <any> 'DateTime',
    Semester = <any> 'Semester',
    GeoCountry = <any> 'GeoCountry',
    GeoState = <any> 'GeoState',
    GeoCounty = <any> 'GeoCounty',
    GeoOther = <any> 'GeoOther',
    GeoCity = <any> 'GeoCity',
    GeoZip = <any> 'GeoZip',
    GeoAddress = <any> 'GeoAddress',
    GeoCustom = <any> 'GeoCustom',
    GeoLongitude = <any> 'GeoLongitude',
    GeoLatitude = <any> 'GeoLatitude',
    MachineLearning = <any> 'MachineLearning',
    ImageUrl = <any> 'ImageUrl',
    Url = <any> 'Url',
    Person = <any> 'Person',
    CustomGeoCategory = <any> 'CustomGeoCategory'
}
