/**
 * Pyramid Analytics Web API
 * Pyramid Analytics Web API enables user applications to manage their pyramid                                             data and settings
 *
 * The version of the OpenAPI document: 2023.12.181
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* The connection string id and the new model process date to be updated. 
*/
export class ModelProcessDateObject {
    /**
    * A flag to indicate whether or not to run all related on-demand schedules attached to this model
    */
    'runOnDemandSchedules'?: boolean;
    /**
    * The connection string ID of the selected semantic/data model
    */
    'connectionStringId': string;
    /**
    * The new process date for the model
    */
    'modelProcessDate': Date;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "runOnDemandSchedules",
            "baseName": "runOnDemandSchedules",
            "type": "boolean"
        },
        {
            "name": "connectionStringId",
            "baseName": "connectionStringId",
            "type": "string"
        },
        {
            "name": "modelProcessDate",
            "baseName": "modelProcessDate",
            "type": "Date"
        }    ];

    static getAttributeTypeMap() {
        return ModelProcessDateObject.attributeTypeMap;
    }
}

