/**
 * Pyramid Analytics Web API
 * Pyramid Analytics Web API enables user applications to manage their pyramid                                             data and settings
 *
 * The version of the OpenAPI document: 2023.12.181
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Column type: regular database table (identified by column and table name) or a calculated column expression
*/
export enum ModelingColumnType {
    Regular = <any> 'Regular',
    CalculatedColumn = <any> 'CalculatedColumn'
}
