"use strict";
/**
 * Pyramid Analytics Web API
 * Pyramid Analytics Web API enables user applications to manage their pyramid                                             data and settings
 *
 * The version of the OpenAPI document: 2023.12.181
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ModifiedItemsResult = void 0;
/**
* Generic API response object with success or failure flag and related messages.
*/
var ModifiedItemsResult = /** @class */ (function () {
    function ModifiedItemsResult() {
    }
    ModifiedItemsResult.getAttributeTypeMap = function () {
        return ModifiedItemsResult.attributeTypeMap;
    };
    ModifiedItemsResult.discriminator = undefined;
    ModifiedItemsResult.attributeTypeMap = [
        {
            "name": "modifiedList",
            "baseName": "modifiedList",
            "type": "Array<ItemId>"
        },
        {
            "name": "success",
            "baseName": "success",
            "type": "boolean"
        },
        {
            "name": "errorMessage",
            "baseName": "errorMessage",
            "type": "string"
        }
    ];
    return ModifiedItemsResult;
}());
exports.ModifiedItemsResult = ModifiedItemsResult;
