/**
 * Pyramid Analytics Web API
 * Pyramid Analytics Web API enables user applications to manage their pyramid                                             data and settings
 *
 * The version of the OpenAPI document: 2023.12.181
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* The listing of content items object.
*/
export class NewFolderApiData {
    /**
    * The system ID of the parent folder for the new folder.
    */
    'parentFolderId': string;
    /**
    * The new folder\'s name
    */
    'folderName': string;
    /**
    * The system ID of the new folder. If provided, the GUID will be used. Otherwise, the function will auto-create it.
    */
    'folderId'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "parentFolderId",
            "baseName": "parentFolderId",
            "type": "string"
        },
        {
            "name": "folderName",
            "baseName": "folderName",
            "type": "string"
        },
        {
            "name": "folderId",
            "baseName": "folderId",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return NewFolderApiData.attributeTypeMap;
    }
}

