"use strict";
/**
 * Pyramid Analytics Web API
 * Pyramid Analytics Web API enables user applications to manage their pyramid                                             data and settings
 *
 * The version of the OpenAPI document: 2023.12.181
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.NlpQueryExportData = void 0;
/**
* The query export object used to specify how to extract nlp query results.
*/
var NlpQueryExportData = /** @class */ (function () {
    function NlpQueryExportData() {
    }
    NlpQueryExportData.getAttributeTypeMap = function () {
        return NlpQueryExportData.attributeTypeMap;
    };
    NlpQueryExportData.discriminator = undefined;
    NlpQueryExportData.attributeTypeMap = [
        {
            "name": "exportOptions",
            "baseName": "exportOptions",
            "type": "ExportOptions"
        },
        {
            "name": "exportType",
            "baseName": "exportType",
            "type": "ApiResponseFormat"
        },
        {
            "name": "model",
            "baseName": "model",
            "type": "string"
        },
        {
            "name": "nlpSentence",
            "baseName": "nlpSentence",
            "type": "string"
        },
        {
            "name": "databaseId",
            "baseName": "databaseId",
            "type": "string"
        },
        {
            "name": "serverId",
            "baseName": "serverId",
            "type": "string"
        }
    ];
    return NlpQueryExportData;
}());
exports.NlpQueryExportData = NlpQueryExportData;
