/**
 * Pyramid Analytics Web API
 * Pyramid Analytics Web API enables user applications to manage their pyramid                                             data and settings
 *
 * The version of the OpenAPI document: 2023.12.181
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* List of notification indicator counts for unread items.
*/
export class NotificationIndicatorsResult {
    /**
    * alert notification count.
    */
    'alerts'?: number;
    /**
    * model notification count.
    */
    'models'?: number;
    /**
    * subscription notification count.
    */
    'subscriptions'?: number;
    /**
    * conversation notification count.
    */
    'conversations'?: number;
    /**
    * publication notification count.
    */
    'publications'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "alerts",
            "baseName": "alerts",
            "type": "number"
        },
        {
            "name": "models",
            "baseName": "models",
            "type": "number"
        },
        {
            "name": "subscriptions",
            "baseName": "subscriptions",
            "type": "number"
        },
        {
            "name": "conversations",
            "baseName": "conversations",
            "type": "number"
        },
        {
            "name": "publications",
            "baseName": "publications",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return NotificationIndicatorsResult.attributeTypeMap;
    }
}

