"use strict";
/**
 * Pyramid Analytics Web API
 * Pyramid Analytics Web API enables user applications to manage their pyramid                                             data and settings
 *
 * The version of the OpenAPI document: 2023.12.181
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.OauthDataSourceSettings = void 0;
/**
* Additional setting for OauthDataSources
*/
var OauthDataSourceSettings = /** @class */ (function () {
    function OauthDataSourceSettings() {
        /**
        * Value used to determine the type of the item receiving, use the class name
        */
        this['inheritanceType'] = 'OauthDataSourceSettings';
    }
    OauthDataSourceSettings.getAttributeTypeMap = function () {
        return OauthDataSourceSettings.attributeTypeMap;
    };
    OauthDataSourceSettings.discriminator = undefined;
    OauthDataSourceSettings.attributeTypeMap = [
        {
            "name": "redirectUri",
            "baseName": "redirectUri",
            "type": "string"
        },
        {
            "name": "clientId",
            "baseName": "clientId",
            "type": "string"
        },
        {
            "name": "loadSuperFromGlobal",
            "baseName": "loadSuperFromGlobal",
            "type": "boolean"
        },
        {
            "name": "scope",
            "baseName": "scope",
            "type": "string"
        },
        {
            "name": "jwksUri",
            "baseName": "jwksUri",
            "type": "string"
        },
        {
            "name": "openIdAuthType",
            "baseName": "openIdAuthType",
            "type": "OpenIdAuthType"
        },
        {
            "name": "clientSecret",
            "baseName": "clientSecret",
            "type": "string"
        },
        {
            "name": "tokenEntryPoint",
            "baseName": "tokenEntryPoint",
            "type": "string"
        },
        {
            "name": "authenticationEndPointUrl",
            "baseName": "authenticationEndPointUrl",
            "type": "string"
        },
        {
            "name": "inheritanceType",
            "baseName": "inheritanceType",
            "type": "string"
        }
    ];
    return OauthDataSourceSettings;
}());
exports.OauthDataSourceSettings = OauthDataSourceSettings;
