"use strict";
/**
 * Pyramid Analytics Web API
 * Pyramid Analytics Web API enables user applications to manage their pyramid                                             data and settings
 *
 * The version of the OpenAPI document: 2023.12.181
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.OpenIdAuthType = void 0;
/**
* OpenId Provider type
*/
var OpenIdAuthType;
(function (OpenIdAuthType) {
    OpenIdAuthType[OpenIdAuthType["None"] = 'None'] = "None";
    OpenIdAuthType[OpenIdAuthType["Microsoft"] = 'Microsoft'] = "Microsoft";
    OpenIdAuthType[OpenIdAuthType["Google"] = 'Google'] = "Google";
    OpenIdAuthType[OpenIdAuthType["Custom"] = 'Custom'] = "Custom";
})(OpenIdAuthType || (exports.OpenIdAuthType = OpenIdAuthType = {}));
