/**
 * Pyramid Analytics Web API
 * Pyramid Analytics Web API enables user applications to manage their pyramid                                             data and settings
 *
 * The version of the OpenAPI document: 2023.12.181
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* OpenId Provider type
*/
export enum OpenIdAuthType {
    None = <any> 'None',
    Microsoft = <any> 'Microsoft',
    Google = <any> 'Google',
    Custom = <any> 'Custom'
}
