/**
 * Pyramid Analytics Web API
 * Pyramid Analytics Web API enables user applications to manage their pyramid                                             data and settings
 *
 * The version of the OpenAPI document: 2023.12.181
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Page size
*/
export enum PaperType {
    Letter = <any> 'Letter',
    A4 = <any> 'A4',
    Legal = <any> 'Legal',
    Tabloid = <any> 'Tabloid',
    A3 = <any> 'A3',
    A5 = <any> 'A5',
    A169 = <any> 'A169',
    A34 = <any> 'A34',
    Viewport = <any> 'Viewport',
    Custom = <any> 'Custom'
}
