/**
 * Pyramid Analytics Web API
 * Pyramid Analytics Web API enables user applications to manage their pyramid                                             data and settings
 *
 * The version of the OpenAPI document: 2023.12.181
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ClashDefaultOption } from './clashDefaultOption';
import { RoleAssignmentType } from './roleAssignmentType';

/**
* The object representing the details for where to import a PIE file of content.
*/
export class PieApiObject {
    /**
    * The PIE file contents (base64 data payload)
    */
    'fileZippedData': string;
    'rolesAssignmentType'?: RoleAssignmentType;
    /**
    * The roles ID\'s to be applied to the imported content. Relevant only for \'RoleAssignmentType.ForceExternalRoles\'
    */
    'roleIds'?: Array<string>;
    /**
    * The system ID of the root folder that will house the imported content
    */
    'rootFolderId': string;
    'clashDefaultOption'?: ClashDefaultOption;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "fileZippedData",
            "baseName": "fileZippedData",
            "type": "string"
        },
        {
            "name": "rolesAssignmentType",
            "baseName": "rolesAssignmentType",
            "type": "RoleAssignmentType"
        },
        {
            "name": "roleIds",
            "baseName": "roleIds",
            "type": "Array<string>"
        },
        {
            "name": "rootFolderId",
            "baseName": "rootFolderId",
            "type": "string"
        },
        {
            "name": "clashDefaultOption",
            "baseName": "clashDefaultOption",
            "type": "ClashDefaultOption"
        }    ];

    static getAttributeTypeMap() {
        return PieApiObject.attributeTypeMap;
    }
}

