"use strict";
/**
 * Pyramid Analytics Web API
 * Pyramid Analytics Web API enables user applications to manage their pyramid                                             data and settings
 *
 * The version of the OpenAPI document: 2023.12.181
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.PrintingSummaryLog = void 0;
var PrintingSummaryLog = /** @class */ (function () {
    function PrintingSummaryLog() {
    }
    PrintingSummaryLog.getAttributeTypeMap = function () {
        return PrintingSummaryLog.attributeTypeMap;
    };
    PrintingSummaryLog.discriminator = undefined;
    PrintingSummaryLog.attributeTypeMap = [
        {
            "name": "outputStatus",
            "baseName": "outputStatus",
            "type": "string"
        },
        {
            "name": "printingDuration",
            "baseName": "printingDuration",
            "type": "string"
        },
        {
            "name": "conversionEndTime",
            "baseName": "conversionEndTime",
            "type": "string"
        },
        {
            "name": "packageId",
            "baseName": "packageId",
            "type": "string"
        },
        {
            "name": "outputType",
            "baseName": "outputType",
            "type": "string"
        },
        {
            "name": "printingError",
            "baseName": "printingError",
            "type": "string"
        },
        {
            "name": "distributionLogs",
            "baseName": "distributionLogs",
            "type": "Array<DistributionLog>"
        },
        {
            "name": "printingDate",
            "baseName": "printingDate",
            "type": "string"
        },
        {
            "name": "packageType",
            "baseName": "packageType",
            "type": "ContentType"
        },
        {
            "name": "componentsLogs",
            "baseName": "componentsLogs",
            "type": "Array<ComponentLog>"
        },
        {
            "name": "printingEndTime",
            "baseName": "printingEndTime",
            "type": "string"
        },
        {
            "name": "conversionStartTime",
            "baseName": "conversionStartTime",
            "type": "string"
        },
        {
            "name": "fileSize",
            "baseName": "fileSize",
            "type": "number"
        },
        {
            "name": "excelDataModel",
            "baseName": "excelDataModel",
            "type": "string"
        },
        {
            "name": "packageName",
            "baseName": "packageName",
            "type": "string"
        },
        {
            "name": "conversionDuration",
            "baseName": "conversionDuration",
            "type": "string"
        },
        {
            "name": "queryLogs",
            "baseName": "queryLogs",
            "type": "Array<QueryLog>"
        },
        {
            "name": "printingStartTime",
            "baseName": "printingStartTime",
            "type": "string"
        }
    ];
    return PrintingSummaryLog;
}());
exports.PrintingSummaryLog = PrintingSummaryLog;
