/**
 * Pyramid Analytics Web API
 * Pyramid Analytics Web API enables user applications to manage their pyramid                                             data and settings
 *
 * The version of the OpenAPI document: 2023.12.181
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ErrorMessage } from './errorMessage';
import { PrintingSummaryLog } from './printingSummaryLog';
import { TaskSummary } from './taskSummary';

export class PrintingSummaryLogHolder extends TaskSummary {
    'printingSummaryLogs'?: Array<PrintingSummaryLog>;
    /**
    * Value used to determine the type of the item receiving, use the class name
    */
    'inheritanceType'?: string = 'PrintingSummaryLogHolder';

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "printingSummaryLogs",
            "baseName": "printingSummaryLogs",
            "type": "Array<PrintingSummaryLog>"
        },
        {
            "name": "inheritanceType",
            "baseName": "inheritanceType",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(PrintingSummaryLogHolder.attributeTypeMap);
    }
}

