"use strict";
/**
 * Pyramid Analytics Web API
 * Pyramid Analytics Web API enables user applications to manage their pyramid                                             data and settings
 *
 * The version of the OpenAPI document: 2023.12.181
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.PrintingOutputType = void 0;
/**
* The result type of the printing process
*/
var PrintingOutputType;
(function (PrintingOutputType) {
    PrintingOutputType[PrintingOutputType["Pdf"] = 'PDF'] = "Pdf";
    PrintingOutputType[PrintingOutputType["Word"] = 'Word'] = "Word";
    PrintingOutputType[PrintingOutputType["PowerPoint"] = 'PowerPoint'] = "PowerPoint";
    PrintingOutputType[PrintingOutputType["Excel"] = 'Excel'] = "Excel";
    PrintingOutputType[PrintingOutputType["Html"] = 'Html'] = "Html";
    PrintingOutputType[PrintingOutputType["Image"] = 'Image'] = "Image";
    PrintingOutputType[PrintingOutputType["NoPrinting"] = 'NoPrinting'] = "NoPrinting";
    PrintingOutputType[PrintingOutputType["Csv"] = 'CSV'] = "Csv";
    PrintingOutputType[PrintingOutputType["Xml"] = 'XML'] = "Xml";
    PrintingOutputType[PrintingOutputType["Json"] = 'JSON'] = "Json";
    PrintingOutputType[PrintingOutputType["Png"] = 'PNG'] = "Png";
    PrintingOutputType[PrintingOutputType["Odata"] = 'ODATA'] = "Odata";
})(PrintingOutputType || (exports.PrintingOutputType = PrintingOutputType = {}));
