/**
 * Pyramid Analytics Web API
 * Pyramid Analytics Web API enables user applications to manage their pyramid                                             data and settings
 *
 * The version of the OpenAPI document: 2023.12.181
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ServiceStatus } from './serviceStatus';

/**
* Data payload with details on the Pulse clients
*/
export class PulseClientData {
    /**
    * The Pulse client\'s ID
    */
    'instanceId'?: string;
    /**
    * The operating system that hosts the Pulse client
    */
    'os'?: string;
    /**
    * The system ID of the hosting tenant
    */
    'tenantId'?: string;
    /**
    * The decorative name of the Pulse client
    */
    'caption'?: string;
    /**
    * Indicator if the Pulse client is enabled for activity of not
    */
    'active'?: boolean;
    /**
    * The version of the Pulse client
    */
    'version'?: string;
    /**
    * The machine name hosting the Pulse client
    */
    'machineName'?: string;
    'status'?: ServiceStatus;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "instanceId",
            "baseName": "instanceId",
            "type": "string"
        },
        {
            "name": "os",
            "baseName": "os",
            "type": "string"
        },
        {
            "name": "tenantId",
            "baseName": "tenantId",
            "type": "string"
        },
        {
            "name": "caption",
            "baseName": "caption",
            "type": "string"
        },
        {
            "name": "active",
            "baseName": "active",
            "type": "boolean"
        },
        {
            "name": "version",
            "baseName": "version",
            "type": "string"
        },
        {
            "name": "machineName",
            "baseName": "machineName",
            "type": "string"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "ServiceStatus"
        }    ];

    static getAttributeTypeMap() {
        return PulseClientData.attributeTypeMap;
    }
}

