"use strict";
/**
 * Pyramid Analytics Web API
 * Pyramid Analytics Web API enables user applications to manage their pyramid                                             data and settings
 *
 * The version of the OpenAPI document: 2023.12.181
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.PyramidContentItem = void 0;
/**
* Pyramid Content item object.
*/
var PyramidContentItem = /** @class */ (function () {
    function PyramidContentItem() {
    }
    PyramidContentItem.getAttributeTypeMap = function () {
        return PyramidContentItem.attributeTypeMap;
    };
    PyramidContentItem.discriminator = undefined;
    PyramidContentItem.attributeTypeMap = [
        {
            "name": "itemType",
            "baseName": "itemType",
            "type": "ItemType"
        },
        {
            "name": "createdDate",
            "baseName": "createdDate",
            "type": "Date"
        },
        {
            "name": "isDeleted",
            "baseName": "isDeleted",
            "type": "boolean"
        },
        {
            "name": "createdBy",
            "baseName": "createdBy",
            "type": "string"
        },
        {
            "name": "modifiedDate",
            "baseName": "modifiedDate",
            "type": "Date"
        },
        {
            "name": "tenantId",
            "baseName": "tenantId",
            "type": "string"
        },
        {
            "name": "caption",
            "baseName": "caption",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "version",
            "baseName": "version",
            "type": "string"
        },
        {
            "name": "contentType",
            "baseName": "contentType",
            "type": "ContentType"
        },
        {
            "name": "parentId",
            "baseName": "parentId",
            "type": "string"
        }
    ];
    return PyramidContentItem;
}());
exports.PyramidContentItem = PyramidContentItem;
