/**
 * Pyramid Analytics Web API
 * Pyramid Analytics Web API enables user applications to manage their pyramid                                             data and settings
 *
 * The version of the OpenAPI document: 2023.12.181
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ExecutionSettings } from './executionSettings';
import { QueryCacheMode } from './queryCacheMode';
import { TotalsSettings } from './totalsSettings';

/**
* Advanced Query Features
*/
export class QueryOptions {
    /**
    * Defines whether to show empty values
    */
    'showEmpties'?: boolean;
    'cacheMode': QueryCacheMode;
    'totalsSettings'?: TotalsSettings;
    'executionSettings'?: ExecutionSettings;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "showEmpties",
            "baseName": "showEmpties",
            "type": "boolean"
        },
        {
            "name": "cacheMode",
            "baseName": "cacheMode",
            "type": "QueryCacheMode"
        },
        {
            "name": "totalsSettings",
            "baseName": "totalsSettings",
            "type": "TotalsSettings"
        },
        {
            "name": "executionSettings",
            "baseName": "executionSettings",
            "type": "ExecutionSettings"
        }    ];

    static getAttributeTypeMap() {
        return QueryOptions.attributeTypeMap;
    }
}

