/**
 * Pyramid Analytics Web API
 * Pyramid Analytics Web API enables user applications to manage their pyramid                                             data and settings
 *
 * The version of the OpenAPI document: 2023.12.181
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ConnectionStringData } from './connectionStringData';
import { ContentType } from './contentType';
import { RootFolderType } from './rootFolderType';

/**
* Represents an item related data
*/
export class RelatedItemData {
    /**
    * The amount of times the items is being used by other items
    */
    'numberOfUsages'?: number;
    /**
    * The item\'s parent folder ID
    */
    'folderId'?: string;
    /**
    * The item\'s folder absolute file path
    */
    'folderPath'?: string;
    /**
    * The related item\'s ID
    */
    'itemId'?: string;
    /**
    * The create date of the item
    */
    'createdDate'?: Date;
    /**
    * The related item\'s children
    */
    'children'?: Array<RelatedItemData>;
    /**
    * The creator\'s user ID
    */
    'createdBy'?: string;
    'dataSourceProperties'?: ConnectionStringData;
    /**
    * The related item\'s name
    */
    'name'?: string;
    'rootFolderType'?: RootFolderType;
    /**
    * The item\'s related tenant ID
    */
    'tenantId'?: string;
    /**
    * Boolean to indicate if the user can change and save the item.
    */
    'hasWriteAccess'?: boolean;
    'contentType'?: ContentType;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "numberOfUsages",
            "baseName": "numberOfUsages",
            "type": "number"
        },
        {
            "name": "folderId",
            "baseName": "folderId",
            "type": "string"
        },
        {
            "name": "folderPath",
            "baseName": "folderPath",
            "type": "string"
        },
        {
            "name": "itemId",
            "baseName": "itemId",
            "type": "string"
        },
        {
            "name": "createdDate",
            "baseName": "createdDate",
            "type": "Date"
        },
        {
            "name": "children",
            "baseName": "children",
            "type": "Array<RelatedItemData>"
        },
        {
            "name": "createdBy",
            "baseName": "createdBy",
            "type": "string"
        },
        {
            "name": "dataSourceProperties",
            "baseName": "dataSourceProperties",
            "type": "ConnectionStringData"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "rootFolderType",
            "baseName": "rootFolderType",
            "type": "RootFolderType"
        },
        {
            "name": "tenantId",
            "baseName": "tenantId",
            "type": "string"
        },
        {
            "name": "hasWriteAccess",
            "baseName": "hasWriteAccess",
            "type": "boolean"
        },
        {
            "name": "contentType",
            "baseName": "contentType",
            "type": "ContentType"
        }    ];

    static getAttributeTypeMap() {
        return RelatedItemData.attributeTypeMap;
    }
}

