"use strict";
/**
 * Pyramid Analytics Web API
 * Pyramid Analytics Web API enables user applications to manage their pyramid                                             data and settings
 *
 * The version of the OpenAPI document: 2023.12.181
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.RolesInItemRemovalObject = void 0;
/**
* The role object with settings to be set for the chosen content item.
*/
var RolesInItemRemovalObject = /** @class */ (function () {
    function RolesInItemRemovalObject() {
    }
    RolesInItemRemovalObject.getAttributeTypeMap = function () {
        return RolesInItemRemovalObject.attributeTypeMap;
    };
    RolesInItemRemovalObject.discriminator = undefined;
    RolesInItemRemovalObject.attributeTypeMap = [
        {
            "name": "itemId",
            "baseName": "itemId",
            "type": "string"
        },
        {
            "name": "roleIds",
            "baseName": "roleIds",
            "type": "Array<string>"
        }
    ];
    return RolesInItemRemovalObject;
}());
exports.RolesInItemRemovalObject = RolesInItemRemovalObject;
