"use strict";
/**
 * Pyramid Analytics Web API
 * Pyramid Analytics Web API enables user applications to manage their pyramid                                             data and settings
 *
 * The version of the OpenAPI document: 2023.12.181
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.RoleAdGroupsModifyObject = void 0;
/**
* The user object contains all relevant meta-data for the user.
*/
var RoleAdGroupsModifyObject = /** @class */ (function () {
    function RoleAdGroupsModifyObject() {
    }
    RoleAdGroupsModifyObject.getAttributeTypeMap = function () {
        return RoleAdGroupsModifyObject.attributeTypeMap;
    };
    RoleAdGroupsModifyObject.discriminator = undefined;
    RoleAdGroupsModifyObject.attributeTypeMap = [
        {
            "name": "groupsToRemove",
            "baseName": "groupsToRemove",
            "type": "Array<LdapGroupIdentifier>"
        },
        {
            "name": "roleId",
            "baseName": "roleId",
            "type": "string"
        },
        {
            "name": "groupsToAdd",
            "baseName": "groupsToAdd",
            "type": "Array<LdapGroupIdentifier>"
        }
    ];
    return RoleAdGroupsModifyObject;
}());
exports.RoleAdGroupsModifyObject = RoleAdGroupsModifyObject;
