"use strict";
/**
 * Pyramid Analytics Web API
 * Pyramid Analytics Web API enables user applications to manage their pyramid                                             data and settings
 *
 * The version of the OpenAPI document: 2023.12.181
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.RoleAssignmentType = void 0;
/**
* The enumeration of role assignment approaches.
*/
var RoleAssignmentType;
(function (RoleAssignmentType) {
    RoleAssignmentType[RoleAssignmentType["UseDefaultBehavior"] = 'UseDefaultBehavior'] = "UseDefaultBehavior";
    RoleAssignmentType[RoleAssignmentType["ForcePackageRoles"] = 'ForcePackageRoles'] = "ForcePackageRoles";
    RoleAssignmentType[RoleAssignmentType["ForceExternalRoles"] = 'ForceExternalRoles'] = "ForceExternalRoles";
    RoleAssignmentType[RoleAssignmentType["ForceParentFolderRoles"] = 'ForceParentFolderRoles'] = "ForceParentFolderRoles";
    RoleAssignmentType[RoleAssignmentType["InheritRolesOnCut"] = 'InheritRolesOnCut'] = "InheritRolesOnCut";
    RoleAssignmentType[RoleAssignmentType["InheritRolesOnCopy"] = 'InheritRolesOnCopy'] = "InheritRolesOnCopy";
})(RoleAssignmentType || (exports.RoleAssignmentType = RoleAssignmentType = {}));
