"use strict";
/**
 * Pyramid Analytics Web API
 * Pyramid Analytics Web API enables user applications to manage their pyramid                                             data and settings
 *
 * The version of the OpenAPI document: 2023.12.181
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.RoleToItemApiData = void 0;
/**
* The role object with settings to be set for the chosen content item.
*/
var RoleToItemApiData = /** @class */ (function () {
    function RoleToItemApiData() {
    }
    RoleToItemApiData.getAttributeTypeMap = function () {
        return RoleToItemApiData.attributeTypeMap;
    };
    RoleToItemApiData.discriminator = undefined;
    RoleToItemApiData.attributeTypeMap = [
        {
            "name": "accessType",
            "baseName": "accessType",
            "type": "AccessType"
        },
        {
            "name": "itemId",
            "baseName": "itemId",
            "type": "string"
        },
        {
            "name": "roleId",
            "baseName": "roleId",
            "type": "string"
        },
        {
            "name": "propagateRoles",
            "baseName": "propagateRoles",
            "type": "boolean"
        }
    ];
    return RoleToItemApiData;
}());
exports.RoleToItemApiData = RoleToItemApiData;
