"use strict";
/**
 * Pyramid Analytics Web API
 * Pyramid Analytics Web API enables user applications to manage their pyramid                                             data and settings
 *
 * The version of the OpenAPI document: 2023.12.181
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ScatterTooltipChip = void 0;
/**
* Settings for the Tooltip drop zone chip for the Scatter visual
*/
var ScatterTooltipChip = /** @class */ (function () {
    function ScatterTooltipChip() {
        /**
        * Value used to determine the type of the item receiving, use the class name
        */
        this['inheritanceType'] = 'ScatterTooltipChip';
    }
    ScatterTooltipChip.getAttributeTypeMap = function () {
        return ScatterTooltipChip.attributeTypeMap;
    };
    ScatterTooltipChip.discriminator = undefined;
    ScatterTooltipChip.attributeTypeMap = [
        {
            "name": "measure",
            "baseName": "measure",
            "type": "ScatterTooltipMeasureChip"
        },
        {
            "name": "hierarchy",
            "baseName": "hierarchy",
            "type": "ScatterTooltipHierarchyChip"
        },
        {
            "name": "inheritanceType",
            "baseName": "inheritanceType",
            "type": "string"
        }
    ];
    return ScatterTooltipChip;
}());
exports.ScatterTooltipChip = ScatterTooltipChip;
