/**
 * Pyramid Analytics Web API
 * Pyramid Analytics Web API enables user applications to manage their pyramid                                             data and settings
 *
 * The version of the OpenAPI document: 2023.12.181
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ScatterFilterHierarchyChip } from './scatterFilterHierarchyChip';
import { ScatterFilterValuesChip } from './scatterFilterValuesChip';

/**
* Settings for the Filter drop zone chip for the Scatter visual
*/
export class ScatterFilterChip {
    'values'?: ScatterFilterValuesChip;
    'hierarchy'?: ScatterFilterHierarchyChip;
    /**
    * Value used to determine the type of the item receiving, use the class name
    */
    'inheritanceType'?: string = 'ScatterFilterChip';

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "values",
            "baseName": "values",
            "type": "ScatterFilterValuesChip"
        },
        {
            "name": "hierarchy",
            "baseName": "hierarchy",
            "type": "ScatterFilterHierarchyChip"
        },
        {
            "name": "inheritanceType",
            "baseName": "inheritanceType",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ScatterFilterChip.attributeTypeMap;
    }
}

