"use strict";
/**
 * Pyramid Analytics Web API
 * Pyramid Analytics Web API enables user applications to manage their pyramid                                             data and settings
 *
 * The version of the OpenAPI document: 2023.12.181
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ScatterVisual = void 0;
/**
* Settings for the Scatter visual
*/
var ScatterVisual = /** @class */ (function () {
    function ScatterVisual() {
        /**
        * Value used to determine the type of the item receiving, use the class name
        */
        this['inheritanceType'] = 'ScatterVisual';
    }
    ScatterVisual.getAttributeTypeMap = function () {
        return ScatterVisual.attributeTypeMap;
    };
    ScatterVisual.discriminator = undefined;
    ScatterVisual.attributeTypeMap = [
        {
            "name": "trellisHorizontal",
            "baseName": "trellisHorizontal",
            "type": "ScatterTrellisHorizontalDropZone"
        },
        {
            "name": "color",
            "baseName": "color",
            "type": "ScatterColorDropZone"
        },
        {
            "name": "motion",
            "baseName": "motion",
            "type": "ScatterMotionDropZone"
        },
        {
            "name": "shape",
            "baseName": "shape",
            "type": "ScatterShapeDropZone"
        },
        {
            "name": "trellisVertical",
            "baseName": "trellisVertical",
            "type": "ScatterTrellisVerticalDropZone"
        },
        {
            "name": "yValues",
            "baseName": "yValues",
            "type": "ScatterYValuesDropZone"
        },
        {
            "name": "tooltip",
            "baseName": "tooltip",
            "type": "ScatterTooltipDropZone"
        },
        {
            "name": "xValues",
            "baseName": "xValues",
            "type": "ScatterXValuesDropZone"
        },
        {
            "name": "labels",
            "baseName": "labels",
            "type": "ScatterLabelsDropZone"
        },
        {
            "name": "filter",
            "baseName": "filter",
            "type": "ScatterFilterDropZone"
        },
        {
            "name": "visualType",
            "baseName": "visualType",
            "type": "ScatterVisualType"
        },
        {
            "name": "size",
            "baseName": "size",
            "type": "ScatterSizeDropZone"
        },
        {
            "name": "details",
            "baseName": "details",
            "type": "ScatterDetailsDropZone"
        },
        {
            "name": "inheritanceType",
            "baseName": "inheritanceType",
            "type": "string"
        }
    ];
    return ScatterVisual;
}());
exports.ScatterVisual = ScatterVisual;
