"use strict";
/**
 * Pyramid Analytics Web API
 * Pyramid Analytics Web API enables user applications to manage their pyramid                                             data and settings
 *
 * The version of the OpenAPI document: 2023.12.181
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ScatterTooltipDropZone = void 0;
/**
* Settings for the Tooltip drop zone for the Scatter visual
*/
var ScatterTooltipDropZone = /** @class */ (function () {
    function ScatterTooltipDropZone() {
        /**
        * Value used to determine the type of the item receiving, use the class name
        */
        this['inheritanceType'] = 'ScatterTooltipDropZone';
    }
    ScatterTooltipDropZone.getAttributeTypeMap = function () {
        return ScatterTooltipDropZone.attributeTypeMap;
    };
    ScatterTooltipDropZone.discriminator = undefined;
    ScatterTooltipDropZone.attributeTypeMap = [
        {
            "name": "dropZoneChips",
            "baseName": "dropZoneChips",
            "type": "Array<ScatterTooltipChip>"
        },
        {
            "name": "inheritanceType",
            "baseName": "inheritanceType",
            "type": "string"
        }
    ];
    return ScatterTooltipDropZone;
}());
exports.ScatterTooltipDropZone = ScatterTooltipDropZone;
