"use strict";
/**
 * Pyramid Analytics Web API
 * Pyramid Analytics Web API enables user applications to manage their pyramid                                             data and settings
 *
 * The version of the OpenAPI document: 2023.12.181
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ScatterColorChip = void 0;
/**
* Settings for the Color drop zone chip for the Scatter visual
*/
var ScatterColorChip = /** @class */ (function () {
    function ScatterColorChip() {
        /**
        * Value used to determine the type of the item receiving, use the class name
        */
        this['inheritanceType'] = 'ScatterColorChip';
    }
    ScatterColorChip.getAttributeTypeMap = function () {
        return ScatterColorChip.attributeTypeMap;
    };
    ScatterColorChip.discriminator = undefined;
    ScatterColorChip.attributeTypeMap = [
        {
            "name": "measure",
            "baseName": "measure",
            "type": "ScatterColorMeasureChip"
        },
        {
            "name": "hierarchy",
            "baseName": "hierarchy",
            "type": "ScatterColorHierarchyChip"
        },
        {
            "name": "inheritanceType",
            "baseName": "inheritanceType",
            "type": "string"
        }
    ];
    return ScatterColorChip;
}());
exports.ScatterColorChip = ScatterColorChip;
