"use strict";
/**
 * Pyramid Analytics Web API
 * Pyramid Analytics Web API enables user applications to manage their pyramid                                             data and settings
 *
 * The version of the OpenAPI document: 2023.12.181
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ScatterShapeMeasureChip = void 0;
/**
* Settings for the Shape measure drop zone chip for the Scatter visual
*/
var ScatterShapeMeasureChip = /** @class */ (function () {
    function ScatterShapeMeasureChip() {
        /**
        * Value used to determine the type of the item receiving, use the class name
        */
        this['inheritanceType'] = 'ScatterShapeMeasureChip';
    }
    ScatterShapeMeasureChip.getAttributeTypeMap = function () {
        return ScatterShapeMeasureChip.attributeTypeMap;
    };
    ScatterShapeMeasureChip.discriminator = undefined;
    ScatterShapeMeasureChip.attributeTypeMap = [
        {
            "name": "uniqueName",
            "baseName": "uniqueName",
            "type": "string"
        },
        {
            "name": "inheritanceType",
            "baseName": "inheritanceType",
            "type": "string"
        }
    ];
    return ScatterShapeMeasureChip;
}());
exports.ScatterShapeMeasureChip = ScatterShapeMeasureChip;
