/**
 * Pyramid Analytics Web API
 * Pyramid Analytics Web API enables user applications to manage their pyramid                                             data and settings
 *
 * The version of the OpenAPI document: 2023.12.181
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* The schedule\'s status
*/
export enum ScheduleStatus {
    Idle = <any> 'IDLE',
    Stopped = <any> 'STOPPED',
    Finished = <any> 'FINISHED',
    Deleted = <any> 'DELETED',
    Hold = <any> 'HOLD',
    Canceled = <any> 'CANCELED',
    DisabledAfterFailures = <any> 'DISABLED_AFTER_FAILURES'
}
