"use strict";
/**
 * Pyramid Analytics Web API
 * Pyramid Analytics Web API enables user applications to manage their pyramid                                             data and settings
 *
 * The version of the OpenAPI document: 2023.12.181
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ScientistPermissions = void 0;
/**
* The functional items to be available in the profile as either a list or a sum index bits. The list will take priority if both are supplied
*/
var ScientistPermissions = /** @class */ (function () {
    function ScientistPermissions() {
    }
    ScientistPermissions.getAttributeTypeMap = function () {
        return ScientistPermissions.attributeTypeMap;
    };
    ScientistPermissions.discriminator = undefined;
    ScientistPermissions.attributeTypeMap = [
        {
            "name": "permissionBitIndexList",
            "baseName": "permissionBitIndexList",
            "type": "Array<ScientistPermissionBitIndex>"
        },
        {
            "name": "numeric",
            "baseName": "numeric",
            "type": "number"
        }
    ];
    return ScientistPermissions;
}());
exports.ScientistPermissions = ScientistPermissions;
