"use strict";
/**
 * Pyramid Analytics Web API
 * Pyramid Analytics Web API enables user applications to manage their pyramid                                             data and settings
 *
 * The version of the OpenAPI document: 2023.12.181
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.SearchRootFolderType = void 0;
/**
* The type of root folder.
*/
var SearchRootFolderType;
(function (SearchRootFolderType) {
    SearchRootFolderType[SearchRootFolderType["Private"] = 'Private'] = "Private";
    SearchRootFolderType[SearchRootFolderType["Public"] = 'Public'] = "Public";
    SearchRootFolderType[SearchRootFolderType["Group"] = 'Group'] = "Group";
    SearchRootFolderType[SearchRootFolderType["OneOff"] = 'OneOff'] = "OneOff";
    SearchRootFolderType[SearchRootFolderType["DeletedContent"] = 'DeletedContent'] = "DeletedContent";
    SearchRootFolderType[SearchRootFolderType["CrossTenant"] = 'CrossTenant'] = "CrossTenant";
    SearchRootFolderType[SearchRootFolderType["Recent"] = 'Recent'] = "Recent";
    SearchRootFolderType[SearchRootFolderType["Favorites"] = 'Favorites'] = "Favorites";
})(SearchRootFolderType || (exports.SearchRootFolderType = SearchRootFolderType = {}));
