"use strict";
/**
 * Pyramid Analytics Web API
 * Pyramid Analytics Web API enables user applications to manage their pyramid                                             data and settings
 *
 * The version of the OpenAPI document: 2023.12.181
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.SearchAdUserGroupsData = void 0;
/**
* The LDAP search object that contains the parameters to be used in Active Directory searches.
*/
var SearchAdUserGroupsData = /** @class */ (function () {
    function SearchAdUserGroupsData() {
    }
    SearchAdUserGroupsData.getAttributeTypeMap = function () {
        return SearchAdUserGroupsData.attributeTypeMap;
    };
    SearchAdUserGroupsData.discriminator = undefined;
    SearchAdUserGroupsData.attributeTypeMap = [
        {
            "name": "domainNetBios",
            "baseName": "domainNetBios",
            "type": "string"
        },
        {
            "name": "userName",
            "baseName": "userName",
            "type": "string"
        }
    ];
    return SearchAdUserGroupsData;
}());
exports.SearchAdUserGroupsData = SearchAdUserGroupsData;
