"use strict";
/**
 * Pyramid Analytics Web API
 * Pyramid Analytics Web API enables user applications to manage their pyramid                                             data and settings
 *
 * The version of the OpenAPI document: 2023.12.181
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.SearchAdGroupUsersData = void 0;
/**
* The LDAP search object that contains the parameters to be used in Active Directory searches.
*/
var SearchAdGroupUsersData = /** @class */ (function () {
    function SearchAdGroupUsersData() {
    }
    SearchAdGroupUsersData.getAttributeTypeMap = function () {
        return SearchAdGroupUsersData.attributeTypeMap;
    };
    SearchAdGroupUsersData.discriminator = undefined;
    SearchAdGroupUsersData.attributeTypeMap = [
        {
            "name": "groupNames",
            "baseName": "groupNames",
            "type": "Array<string>"
        },
        {
            "name": "domainNetBios",
            "baseName": "domainNetBios",
            "type": "string"
        }
    ];
    return SearchAdGroupUsersData;
}());
exports.SearchAdGroupUsersData = SearchAdGroupUsersData;
