/**
 * Pyramid Analytics Web API
 * Pyramid Analytics Web API enables user applications to manage their pyramid                                             data and settings
 *
 * The version of the OpenAPI document: 2023.12.181
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* The LDAP search object that contains the parameters to be used in Active Directory searches.
*/
export class SearchAdGroupUsersData {
    /**
    * An array of AD group names to be used for searching
    */
    'groupNames': Array<string>;
    /**
    * The AD domain
    */
    'domainNetBios': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "groupNames",
            "baseName": "groupNames",
            "type": "Array<string>"
        },
        {
            "name": "domainNetBios",
            "baseName": "domainNetBios",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return SearchAdGroupUsersData.attributeTypeMap;
    }
}

