/**
 * Pyramid Analytics Web API
 * Pyramid Analytics Web API enables user applications to manage their pyramid                                             data and settings
 *
 * The version of the OpenAPI document: 2023.12.181
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* The active directory provider type.
*/
export enum SecurityType {
    ActiveDirectory = <any> 'ACTIVE_DIRECTORY',
    ApacheDirectory = <any> 'APACHE_DIRECTORY',
    OpenLdap = <any> 'OPEN_LDAP',
    LocalOs = <any> 'LOCAL_OS',
    AzureActiveDirectory = <any> 'AZURE_ACTIVE_DIRECTORY',
    Saml = <any> 'SAML',
    OpenidConnect = <any> 'OPENID_CONNECT'
}
