"use strict";
/**
 * Pyramid Analytics Web API
 * Pyramid Analytics Web API enables user applications to manage their pyramid                                             data and settings
 *
 * The version of the OpenAPI document: 2023.12.181
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.SegmentVisual = void 0;
/**
* Settings for the Segment visual
*/
var SegmentVisual = /** @class */ (function () {
    function SegmentVisual() {
        /**
        * Value used to determine the type of the item receiving, use the class name
        */
        this['inheritanceType'] = 'SegmentVisual';
    }
    SegmentVisual.getAttributeTypeMap = function () {
        return SegmentVisual.attributeTypeMap;
    };
    SegmentVisual.discriminator = undefined;
    SegmentVisual.attributeTypeMap = [
        {
            "name": "filter",
            "baseName": "filter",
            "type": "SegmentFilterDropZone"
        },
        {
            "name": "visualType",
            "baseName": "visualType",
            "type": "SegmentVisualType"
        },
        {
            "name": "trellisHorizontal",
            "baseName": "trellisHorizontal",
            "type": "SegmentTrellisHorizontalDropZone"
        },
        {
            "name": "color",
            "baseName": "color",
            "type": "SegmentColorDropZone"
        },
        {
            "name": "size",
            "baseName": "size",
            "type": "SegmentSizeDropZone"
        },
        {
            "name": "motion",
            "baseName": "motion",
            "type": "SegmentMotionDropZone"
        },
        {
            "name": "trellisVertical",
            "baseName": "trellisVertical",
            "type": "SegmentTrellisVerticalDropZone"
        },
        {
            "name": "values",
            "baseName": "values",
            "type": "SegmentValuesDropZone"
        },
        {
            "name": "tooltip",
            "baseName": "tooltip",
            "type": "SegmentTooltipDropZone"
        },
        {
            "name": "details",
            "baseName": "details",
            "type": "SegmentDetailsDropZone"
        },
        {
            "name": "labels",
            "baseName": "labels",
            "type": "SegmentLabelsDropZone"
        },
        {
            "name": "inheritanceType",
            "baseName": "inheritanceType",
            "type": "string"
        }
    ];
    return SegmentVisual;
}());
exports.SegmentVisual = SegmentVisual;
