/**
 * Pyramid Analytics Web API
 * Pyramid Analytics Web API enables user applications to manage their pyramid                                             data and settings
 *
 * The version of the OpenAPI document: 2023.12.181
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { FilterHierarchyType } from './filterHierarchyType';

/**
* Settings for the Filter hierarchy drop zone chip for the Segment visual
*/
export class SegmentFilterHierarchyChip {
    /**
    * The unique name of the hierarchy or attribute 
    */
    'uniqueName': string;
    'filterType'?: FilterHierarchyType;
    /**
    * Value used to determine the type of the item receiving, use the class name
    */
    'inheritanceType'?: string = 'SegmentFilterHierarchyChip';

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "uniqueName",
            "baseName": "uniqueName",
            "type": "string"
        },
        {
            "name": "filterType",
            "baseName": "filterType",
            "type": "FilterHierarchyType"
        },
        {
            "name": "inheritanceType",
            "baseName": "inheritanceType",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return SegmentFilterHierarchyChip.attributeTypeMap;
    }
}

