"use strict";
/**
 * Pyramid Analytics Web API
 * Pyramid Analytics Web API enables user applications to manage their pyramid                                             data and settings
 *
 * The version of the OpenAPI document: 2023.12.181
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.SegmentTooltipChip = void 0;
/**
* Settings for the Tooltip drop zone chip for the Segment visual
*/
var SegmentTooltipChip = /** @class */ (function () {
    function SegmentTooltipChip() {
        /**
        * Value used to determine the type of the item receiving, use the class name
        */
        this['inheritanceType'] = 'SegmentTooltipChip';
    }
    SegmentTooltipChip.getAttributeTypeMap = function () {
        return SegmentTooltipChip.attributeTypeMap;
    };
    SegmentTooltipChip.discriminator = undefined;
    SegmentTooltipChip.attributeTypeMap = [
        {
            "name": "measure",
            "baseName": "measure",
            "type": "SegmentTooltipMeasureChip"
        },
        {
            "name": "hierarchy",
            "baseName": "hierarchy",
            "type": "SegmentTooltipHierarchyChip"
        },
        {
            "name": "inheritanceType",
            "baseName": "inheritanceType",
            "type": "string"
        }
    ];
    return SegmentTooltipChip;
}());
exports.SegmentTooltipChip = SegmentTooltipChip;
