"use strict";
/**
 * Pyramid Analytics Web API
 * Pyramid Analytics Web API enables user applications to manage their pyramid                                             data and settings
 *
 * The version of the OpenAPI document: 2023.12.181
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.SegmentValuesDropZone = void 0;
/**
* Settings for the Values drop zone for the Segment visual
*/
var SegmentValuesDropZone = /** @class */ (function () {
    function SegmentValuesDropZone() {
        /**
        * Value used to determine the type of the item receiving, use the class name
        */
        this['inheritanceType'] = 'SegmentValuesDropZone';
    }
    SegmentValuesDropZone.getAttributeTypeMap = function () {
        return SegmentValuesDropZone.attributeTypeMap;
    };
    SegmentValuesDropZone.discriminator = undefined;
    SegmentValuesDropZone.attributeTypeMap = [
        {
            "name": "dropZoneChips",
            "baseName": "dropZoneChips",
            "type": "Array<SegmentValuesMeasureChip>"
        },
        {
            "name": "inheritanceType",
            "baseName": "inheritanceType",
            "type": "string"
        }
    ];
    return SegmentValuesDropZone;
}());
exports.SegmentValuesDropZone = SegmentValuesDropZone;
