"use strict";
/**
 * Pyramid Analytics Web API
 * Pyramid Analytics Web API enables user applications to manage their pyramid                                             data and settings
 *
 * The version of the OpenAPI document: 2023.12.181
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.SegmentFilterChip = void 0;
/**
* Settings for the Filter drop zone chip for the Segment visual
*/
var SegmentFilterChip = /** @class */ (function () {
    function SegmentFilterChip() {
        /**
        * Value used to determine the type of the item receiving, use the class name
        */
        this['inheritanceType'] = 'SegmentFilterChip';
    }
    SegmentFilterChip.getAttributeTypeMap = function () {
        return SegmentFilterChip.attributeTypeMap;
    };
    SegmentFilterChip.discriminator = undefined;
    SegmentFilterChip.attributeTypeMap = [
        {
            "name": "values",
            "baseName": "values",
            "type": "SegmentFilterValuesChip"
        },
        {
            "name": "hierarchy",
            "baseName": "hierarchy",
            "type": "SegmentFilterHierarchyChip"
        },
        {
            "name": "inheritanceType",
            "baseName": "inheritanceType",
            "type": "string"
        }
    ];
    return SegmentFilterChip;
}());
exports.SegmentFilterChip = SegmentFilterChip;
