/**
 * Pyramid Analytics Web API
 * Pyramid Analytics Web API enables user applications to manage their pyramid                                             data and settings
 *
 * The version of the OpenAPI document: 2023.12.181
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { SegmentTrellisVerticalHierarchyChip } from './segmentTrellisVerticalHierarchyChip';
import { SegmentTrellisVerticalValuesChip } from './segmentTrellisVerticalValuesChip';

/**
* Settings for the TrellisVertical drop zone chip for the Segment visual
*/
export class SegmentTrellisVerticalChip {
    'values'?: SegmentTrellisVerticalValuesChip;
    'hierarchy'?: SegmentTrellisVerticalHierarchyChip;
    /**
    * Value used to determine the type of the item receiving, use the class name
    */
    'inheritanceType'?: string = 'SegmentTrellisVerticalChip';

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "values",
            "baseName": "values",
            "type": "SegmentTrellisVerticalValuesChip"
        },
        {
            "name": "hierarchy",
            "baseName": "hierarchy",
            "type": "SegmentTrellisVerticalHierarchyChip"
        },
        {
            "name": "inheritanceType",
            "baseName": "inheritanceType",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return SegmentTrellisVerticalChip.attributeTypeMap;
    }
}

