"use strict";
/**
 * Pyramid Analytics Web API
 * Pyramid Analytics Web API enables user applications to manage their pyramid                                             data and settings
 *
 * The version of the OpenAPI document: 2023.12.181
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ServerAuthenticationMethod = void 0;
/**
* The data source security type enumeration.
*/
var ServerAuthenticationMethod;
(function (ServerAuthenticationMethod) {
    ServerAuthenticationMethod[ServerAuthenticationMethod["UserPassword"] = 'UserPassword'] = "UserPassword";
    ServerAuthenticationMethod[ServerAuthenticationMethod["GlobalActiveDirectory"] = 'GlobalActiveDirectory'] = "GlobalActiveDirectory";
    ServerAuthenticationMethod[ServerAuthenticationMethod["SpecificActiveDirectory"] = 'SpecificActiveDirectory'] = "SpecificActiveDirectory";
    ServerAuthenticationMethod[ServerAuthenticationMethod["ServiceAccount"] = 'ServiceAccount'] = "ServiceAccount";
    ServerAuthenticationMethod[ServerAuthenticationMethod["EndUser"] = 'EndUser'] = "EndUser";
    ServerAuthenticationMethod[ServerAuthenticationMethod["DefaultAwsCredentialsProviderChain"] = 'DefaultAWSCredentialsProviderChain'] = "DefaultAwsCredentialsProviderChain";
    ServerAuthenticationMethod[ServerAuthenticationMethod["Keytab"] = 'Keytab'] = "Keytab";
    ServerAuthenticationMethod[ServerAuthenticationMethod["Snc"] = 'SNC'] = "Snc";
    ServerAuthenticationMethod[ServerAuthenticationMethod["SapLogonTicket"] = 'SAP_LOGON_TICKET'] = "SapLogonTicket";
    ServerAuthenticationMethod[ServerAuthenticationMethod["Saml"] = 'SAML'] = "Saml";
    ServerAuthenticationMethod[ServerAuthenticationMethod["SharepointAppOnly"] = 'SharepointAppOnly'] = "SharepointAppOnly";
    ServerAuthenticationMethod[ServerAuthenticationMethod["SapLogonTicketCustomData"] = 'SAP_LOGON_TICKET_CUSTOM_DATA'] = "SapLogonTicketCustomData";
    ServerAuthenticationMethod[ServerAuthenticationMethod["Oauth"] = 'OAUTH'] = "Oauth";
    ServerAuthenticationMethod[ServerAuthenticationMethod["EndUserOauth"] = 'END_USER_OAUTH'] = "EndUserOauth";
    ServerAuthenticationMethod[ServerAuthenticationMethod["SpecificToken"] = 'SpecificToken'] = "SpecificToken";
})(ServerAuthenticationMethod || (exports.ServerAuthenticationMethod = ServerAuthenticationMethod = {}));
