"use strict";
/**
 * Pyramid Analytics Web API
 * Pyramid Analytics Web API enables user applications to manage their pyramid                                             data and settings
 *
 * The version of the OpenAPI document: 2023.12.181
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ServerData = void 0;
/**
* The data source server object and its settings.
*/
var ServerData = /** @class */ (function () {
    function ServerData() {
    }
    ServerData.getAttributeTypeMap = function () {
        return ServerData.attributeTypeMap;
    };
    ServerData.discriminator = undefined;
    ServerData.attributeTypeMap = [
        {
            "name": "instanceName",
            "baseName": "instanceName",
            "type": "string"
        },
        {
            "name": "overlayPyramidSecurity",
            "baseName": "overlayPyramidSecurity",
            "type": "boolean"
        },
        {
            "name": "useGlobalAccount",
            "baseName": "useGlobalAccount",
            "type": "boolean"
        },
        {
            "name": "serverName",
            "baseName": "serverName",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "securedByUser",
            "baseName": "securedByUser",
            "type": "boolean"
        },
        {
            "name": "userName",
            "baseName": "userName",
            "type": "string"
        },
        {
            "name": "writeCapable",
            "baseName": "writeCapable",
            "type": "number"
        },
        {
            "name": "password",
            "baseName": "password",
            "type": "string"
        },
        {
            "name": "defaultDatabaseName",
            "baseName": "defaultDatabaseName",
            "type": "string"
        },
        {
            "name": "serverAuthenticationMethod",
            "baseName": "serverAuthenticationMethod",
            "type": "ServerAuthenticationMethod"
        },
        {
            "name": "port",
            "baseName": "port",
            "type": "number"
        },
        {
            "name": "pulseClient",
            "baseName": "pulseClient",
            "type": "string"
        },
        {
            "name": "serverType",
            "baseName": "serverType",
            "type": "ConnectionStringType"
        },
        {
            "name": "tenantId",
            "baseName": "tenantId",
            "type": "string"
        },
        {
            "name": "modifiedDate",
            "baseName": "modifiedDate",
            "type": "Date"
        },
        {
            "name": "serverIp",
            "baseName": "serverIp",
            "type": "string"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "additionalServerProperties",
            "baseName": "additionalServerProperties",
            "type": "AdditionalServerProperties"
        },
        {
            "name": "displayFolder",
            "baseName": "displayFolder",
            "type": "string"
        },
        {
            "name": "optionalParameters",
            "baseName": "optionalParameters",
            "type": "string"
        }
    ];
    return ServerData;
}());
exports.ServerData = ServerData;
