"use strict";
/**
 * Pyramid Analytics Web API
 * Pyramid Analytics Web API enables user applications to manage their pyramid                                             data and settings
 *
 * The version of the OpenAPI document: 2023.12.181
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ServerEffectiveUserName = void 0;
/**
* The user\'s effective name type
*/
var ServerEffectiveUserName;
(function (ServerEffectiveUserName) {
    ServerEffectiveUserName[ServerEffectiveUserName["ProxyAccount"] = 'ProxyAccount'] = "ProxyAccount";
    ServerEffectiveUserName[ServerEffectiveUserName["ProxyAccount2"] = 'ProxyAccount2'] = "ProxyAccount2";
})(ServerEffectiveUserName || (exports.ServerEffectiveUserName = ServerEffectiveUserName = {}));
