/**
 * Pyramid Analytics Web API
 * Pyramid Analytics Web API enables user applications to manage their pyramid                                             data and settings
 *
 * The version of the OpenAPI document: 2023.12.181
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { TabularColorDropZone } from './tabularColorDropZone';
import { TabularColsDropZone } from './tabularColsDropZone';
import { TabularFilterDropZone } from './tabularFilterDropZone';
import { TabularSizeDropZone } from './tabularSizeDropZone';
import { TabularTooltipDropZone } from './tabularTooltipDropZone';

/**
* Settings for the Tabular visual
*/
export class TabularVisual {
    'filter'?: TabularFilterDropZone;
    'color'?: TabularColorDropZone;
    'size'?: TabularSizeDropZone;
    'tooltip'?: TabularTooltipDropZone;
    'cols'?: TabularColsDropZone;
    /**
    * Value used to determine the type of the item receiving, use the class name
    */
    'inheritanceType'?: string = 'TabularVisual';

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "filter",
            "baseName": "filter",
            "type": "TabularFilterDropZone"
        },
        {
            "name": "color",
            "baseName": "color",
            "type": "TabularColorDropZone"
        },
        {
            "name": "size",
            "baseName": "size",
            "type": "TabularSizeDropZone"
        },
        {
            "name": "tooltip",
            "baseName": "tooltip",
            "type": "TabularTooltipDropZone"
        },
        {
            "name": "cols",
            "baseName": "cols",
            "type": "TabularColsDropZone"
        },
        {
            "name": "inheritanceType",
            "baseName": "inheritanceType",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return TabularVisual.attributeTypeMap;
    }
}

