"use strict";
/**
 * Pyramid Analytics Web API
 * Pyramid Analytics Web API enables user applications to manage their pyramid                                             data and settings
 *
 * The version of the OpenAPI document: 2023.12.181
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.TabularColorDropZone = void 0;
/**
* Settings for the Color drop zone for the Tabular visual
*/
var TabularColorDropZone = /** @class */ (function () {
    function TabularColorDropZone() {
        /**
        * Value used to determine the type of the item receiving, use the class name
        */
        this['inheritanceType'] = 'TabularColorDropZone';
    }
    TabularColorDropZone.getAttributeTypeMap = function () {
        return TabularColorDropZone.attributeTypeMap;
    };
    TabularColorDropZone.discriminator = undefined;
    TabularColorDropZone.attributeTypeMap = [
        {
            "name": "dropZoneChips",
            "baseName": "dropZoneChips",
            "type": "Array<TabularColorChip>"
        },
        {
            "name": "inheritanceType",
            "baseName": "inheritanceType",
            "type": "string"
        }
    ];
    return TabularColorDropZone;
}());
exports.TabularColorDropZone = TabularColorDropZone;
