"use strict";
/**
 * Pyramid Analytics Web API
 * Pyramid Analytics Web API enables user applications to manage their pyramid                                             data and settings
 *
 * The version of the OpenAPI document: 2023.12.181
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.TabularFilterHierarchyChip = void 0;
/**
* Settings for the Filter hierarchy drop zone chip for the Tabular visual
*/
var TabularFilterHierarchyChip = /** @class */ (function () {
    function TabularFilterHierarchyChip() {
        /**
        * Value used to determine the type of the item receiving, use the class name
        */
        this['inheritanceType'] = 'TabularFilterHierarchyChip';
    }
    TabularFilterHierarchyChip.getAttributeTypeMap = function () {
        return TabularFilterHierarchyChip.attributeTypeMap;
    };
    TabularFilterHierarchyChip.discriminator = undefined;
    TabularFilterHierarchyChip.attributeTypeMap = [
        {
            "name": "uniqueName",
            "baseName": "uniqueName",
            "type": "string"
        },
        {
            "name": "filterType",
            "baseName": "filterType",
            "type": "FilterHierarchyType"
        },
        {
            "name": "inheritanceType",
            "baseName": "inheritanceType",
            "type": "string"
        }
    ];
    return TabularFilterHierarchyChip;
}());
exports.TabularFilterHierarchyChip = TabularFilterHierarchyChip;
