"use strict";
/**
 * Pyramid Analytics Web API
 * Pyramid Analytics Web API enables user applications to manage their pyramid                                             data and settings
 *
 * The version of the OpenAPI document: 2023.12.181
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.TabularTooltipMeasureChip = void 0;
/**
* Settings for the Tooltip measure drop zone chip for the Tabular visual
*/
var TabularTooltipMeasureChip = /** @class */ (function () {
    function TabularTooltipMeasureChip() {
        /**
        * Value used to determine the type of the item receiving, use the class name
        */
        this['inheritanceType'] = 'TabularTooltipMeasureChip';
    }
    TabularTooltipMeasureChip.getAttributeTypeMap = function () {
        return TabularTooltipMeasureChip.attributeTypeMap;
    };
    TabularTooltipMeasureChip.discriminator = undefined;
    TabularTooltipMeasureChip.attributeTypeMap = [
        {
            "name": "uniqueName",
            "baseName": "uniqueName",
            "type": "string"
        },
        {
            "name": "inheritanceType",
            "baseName": "inheritanceType",
            "type": "string"
        }
    ];
    return TabularTooltipMeasureChip;
}());
exports.TabularTooltipMeasureChip = TabularTooltipMeasureChip;
