"use strict";
/**
 * Pyramid Analytics Web API
 * Pyramid Analytics Web API enables user applications to manage their pyramid                                             data and settings
 *
 * The version of the OpenAPI document: 2023.12.181
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.TabularColorMeasureChip = void 0;
/**
* Settings for the Color measure drop zone chip for the Tabular visual
*/
var TabularColorMeasureChip = /** @class */ (function () {
    function TabularColorMeasureChip() {
        /**
        * Value used to determine the type of the item receiving, use the class name
        */
        this['inheritanceType'] = 'TabularColorMeasureChip';
    }
    TabularColorMeasureChip.getAttributeTypeMap = function () {
        return TabularColorMeasureChip.attributeTypeMap;
    };
    TabularColorMeasureChip.discriminator = undefined;
    TabularColorMeasureChip.attributeTypeMap = [
        {
            "name": "uniqueName",
            "baseName": "uniqueName",
            "type": "string"
        },
        {
            "name": "mathFunction",
            "baseName": "mathFunction",
            "type": "ColorMathFunction"
        },
        {
            "name": "targetMeasure",
            "baseName": "targetMeasure",
            "type": "string"
        },
        {
            "name": "inheritanceType",
            "baseName": "inheritanceType",
            "type": "string"
        }
    ];
    return TabularColorMeasureChip;
}());
exports.TabularColorMeasureChip = TabularColorMeasureChip;
