"use strict";
/**
 * Pyramid Analytics Web API
 * Pyramid Analytics Web API enables user applications to manage their pyramid                                             data and settings
 *
 * The version of the OpenAPI document: 2023.12.181
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.TabularColorChip = void 0;
/**
* Settings for the Color drop zone chip for the Tabular visual
*/
var TabularColorChip = /** @class */ (function () {
    function TabularColorChip() {
        /**
        * Value used to determine the type of the item receiving, use the class name
        */
        this['inheritanceType'] = 'TabularColorChip';
    }
    TabularColorChip.getAttributeTypeMap = function () {
        return TabularColorChip.attributeTypeMap;
    };
    TabularColorChip.discriminator = undefined;
    TabularColorChip.attributeTypeMap = [
        {
            "name": "measure",
            "baseName": "measure",
            "type": "TabularColorMeasureChip"
        },
        {
            "name": "hierarchy",
            "baseName": "hierarchy",
            "type": "TabularColorHierarchyChip"
        },
        {
            "name": "inheritanceType",
            "baseName": "inheritanceType",
            "type": "string"
        }
    ];
    return TabularColorChip;
}());
exports.TabularColorChip = TabularColorChip;
