"use strict";
/**
 * Pyramid Analytics Web API
 * Pyramid Analytics Web API enables user applications to manage their pyramid                                             data and settings
 *
 * The version of the OpenAPI document: 2023.12.181
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.TabularColsChip = void 0;
/**
* Settings for the Cols drop zone chip for the Tabular visual
*/
var TabularColsChip = /** @class */ (function () {
    function TabularColsChip() {
        /**
        * Value used to determine the type of the item receiving, use the class name
        */
        this['inheritanceType'] = 'TabularColsChip';
    }
    TabularColsChip.getAttributeTypeMap = function () {
        return TabularColsChip.attributeTypeMap;
    };
    TabularColsChip.discriminator = undefined;
    TabularColsChip.attributeTypeMap = [
        {
            "name": "measure",
            "baseName": "measure",
            "type": "TabularColsMeasureChip"
        },
        {
            "name": "hierarchy",
            "baseName": "hierarchy",
            "type": "TabularColsHierarchyChip"
        },
        {
            "name": "inheritanceType",
            "baseName": "inheritanceType",
            "type": "string"
        }
    ];
    return TabularColsChip;
}());
exports.TabularColsChip = TabularColsChip;
