"use strict";
/**
 * Pyramid Analytics Web API
 * Pyramid Analytics Web API enables user applications to manage their pyramid                                             data and settings
 *
 * The version of the OpenAPI document: 2023.12.181
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.TabularTooltipHierarchyChip = void 0;
/**
* Settings for the Tooltip hierarchy drop zone chip for the Tabular visual
*/
var TabularTooltipHierarchyChip = /** @class */ (function () {
    function TabularTooltipHierarchyChip() {
        /**
        * Value used to determine the type of the item receiving, use the class name
        */
        this['inheritanceType'] = 'TabularTooltipHierarchyChip';
    }
    TabularTooltipHierarchyChip.getAttributeTypeMap = function () {
        return TabularTooltipHierarchyChip.attributeTypeMap;
    };
    TabularTooltipHierarchyChip.discriminator = undefined;
    TabularTooltipHierarchyChip.attributeTypeMap = [
        {
            "name": "uniqueName",
            "baseName": "uniqueName",
            "type": "string"
        },
        {
            "name": "inheritanceType",
            "baseName": "inheritanceType",
            "type": "string"
        }
    ];
    return TabularTooltipHierarchyChip;
}());
exports.TabularTooltipHierarchyChip = TabularTooltipHierarchyChip;
