"use strict";
/**
 * Pyramid Analytics Web API
 * Pyramid Analytics Web API enables user applications to manage their pyramid                                             data and settings
 *
 * The version of the OpenAPI document: 2023.12.181
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.TaskUserApiData = void 0;
/**
* An object specifying the requested task id and user id .
*/
var TaskUserApiData = /** @class */ (function () {
    function TaskUserApiData() {
    }
    TaskUserApiData.getAttributeTypeMap = function () {
        return TaskUserApiData.attributeTypeMap;
    };
    TaskUserApiData.discriminator = undefined;
    TaskUserApiData.attributeTypeMap = [
        {
            "name": "userId",
            "baseName": "userId",
            "type": "string"
        },
        {
            "name": "taskId",
            "baseName": "taskId",
            "type": "string"
        }
    ];
    return TaskUserApiData;
}());
exports.TaskUserApiData = TaskUserApiData;
