/**
 * Pyramid Analytics Web API
 * Pyramid Analytics Web API enables user applications to manage their pyramid                                             data and settings
 *
 * The version of the OpenAPI document: 2023.12.181
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ContentType } from './contentType';
import { PrintingOutputType } from './printingOutputType';
import { ScheduleType } from './scheduleType';
import { TaskStatus } from './taskStatus';
import { TaskSummary } from './taskSummary';

/**
* Execution Tasks object with details of a scheduled job task.
*/
export class TaskViewData {
    /**
    * The task\'s summary
    */
    'summary'?: string;
    /**
    * The task\'s related Schedule name
    */
    'scheduleName'?: string;
    /**
    * The task\'s related item ID
    */
    'scheduleItemId'?: string;
    /**
    * The task\'s executor\'s ID
    */
    'executorId'?: string;
    /**
    * The task\'s end date
    */
    'endDate'?: Date;
    /**
    * The task\'s time zone ID
    */
    'timeZoneId'?: string;
    /**
    * The task\'s description
    */
    'description'?: string;
    'outputType'?: PrintingOutputType;
    'taskSummary'?: TaskSummary;
    /**
    * The task\'s processing machine
    */
    'executorDescription'?: string;
    /**
    * The task\'s result
    */
    'result'?: string;
    /**
    * The task\'s summary formatted for user
    */
    'formattedSummary'?: string;
    /**
    * The task\'s first output ID, there could be multiple outputs
    */
    'outputId'?: string;
    /**
    * The task\'s creation date
    */
    'createdDate'?: Date;
    'scheduleType'?: ScheduleType;
    /**
    * The task\'s related schedule creator
    */
    'createdBy'?: string;
    /**
    * The task\'s system ID
    */
    'id'?: string;
    'contentType'?: ContentType;
    /**
    * The task\'s start date
    */
    'startDate'?: Date;
    /**
    * The task\'s related schedule ID
    */
    'scheduleId'?: string;
    'status'?: TaskStatus;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "summary",
            "baseName": "summary",
            "type": "string"
        },
        {
            "name": "scheduleName",
            "baseName": "scheduleName",
            "type": "string"
        },
        {
            "name": "scheduleItemId",
            "baseName": "scheduleItemId",
            "type": "string"
        },
        {
            "name": "executorId",
            "baseName": "executorId",
            "type": "string"
        },
        {
            "name": "endDate",
            "baseName": "endDate",
            "type": "Date"
        },
        {
            "name": "timeZoneId",
            "baseName": "timeZoneId",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "outputType",
            "baseName": "outputType",
            "type": "PrintingOutputType"
        },
        {
            "name": "taskSummary",
            "baseName": "taskSummary",
            "type": "TaskSummary"
        },
        {
            "name": "executorDescription",
            "baseName": "executorDescription",
            "type": "string"
        },
        {
            "name": "result",
            "baseName": "result",
            "type": "string"
        },
        {
            "name": "formattedSummary",
            "baseName": "formattedSummary",
            "type": "string"
        },
        {
            "name": "outputId",
            "baseName": "outputId",
            "type": "string"
        },
        {
            "name": "createdDate",
            "baseName": "createdDate",
            "type": "Date"
        },
        {
            "name": "scheduleType",
            "baseName": "scheduleType",
            "type": "ScheduleType"
        },
        {
            "name": "createdBy",
            "baseName": "createdBy",
            "type": "string"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "contentType",
            "baseName": "contentType",
            "type": "ContentType"
        },
        {
            "name": "startDate",
            "baseName": "startDate",
            "type": "Date"
        },
        {
            "name": "scheduleId",
            "baseName": "scheduleId",
            "type": "string"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "TaskStatus"
        }    ];

    static getAttributeTypeMap() {
        return TaskViewData.attributeTypeMap;
    }
}

