/**
 * Pyramid Analytics Web API
 * Pyramid Analytics Web API enables user applications to manage their pyramid                                             data and settings
 *
 * The version of the OpenAPI document: 2023.12.181
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ClientLicenseType } from './clientLicenseType';

/**
* The tenant license object with its license type.
*/
export class TenantLicenseTypeData {
    'licenseType': ClientLicenseType;
    /**
    * The tenant\'s system ID
    */
    'tenantId': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "licenseType",
            "baseName": "licenseType",
            "type": "ClientLicenseType"
        },
        {
            "name": "tenantId",
            "baseName": "tenantId",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return TenantLicenseTypeData.attributeTypeMap;
    }
}

