"use strict";
/**
 * Pyramid Analytics Web API
 * Pyramid Analytics Web API enables user applications to manage their pyramid                                             data and settings
 *
 * The version of the OpenAPI document: 2023.12.181
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.TenantSettings = void 0;
/**
* The tenant\'s miscellaneous settings.
*/
var TenantSettings = /** @class */ (function () {
    function TenantSettings() {
    }
    TenantSettings.getAttributeTypeMap = function () {
        return TenantSettings.attributeTypeMap;
    };
    TenantSettings.discriminator = undefined;
    TenantSettings.attributeTypeMap = [
        {
            "name": "showGroupFolder",
            "baseName": "showGroupFolder",
            "type": "boolean"
        },
        {
            "name": "organizationalUnitText",
            "baseName": "organizationalUnitText",
            "type": "string"
        },
        {
            "name": "isOrganizationalUnitOn",
            "baseName": "isOrganizationalUnitOn",
            "type": "boolean"
        },
        {
            "name": "domainName",
            "baseName": "domainName",
            "type": "string"
        },
        {
            "name": "allowWebhookChannels",
            "baseName": "allowWebhookChannels",
            "type": "boolean"
        },
        {
            "name": "firstWorkday",
            "baseName": "firstWorkday",
            "type": "FirstWorkday"
        },
        {
            "name": "defaultPaperType",
            "baseName": "defaultPaperType",
            "type": "PaperType"
        }
    ];
    return TenantSettings;
}());
exports.TenantSettings = TenantSettings;
