/**
 * Pyramid Analytics Web API
 * Pyramid Analytics Web API enables user applications to manage their pyramid                                             data and settings
 *
 * The version of the OpenAPI document: 2023.12.181
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* The theme object holding the definition of a theme.
*/
export class ThemeApiObject {
    /**
    * The theme name. If provided, the name will be used. Otherwise, the function will use the original theme name.
    */
    'themeName'?: string;
    /**
    * The encrypted theme data
    */
    'themeData': string;
    /**
    * Boolean of whether theme is default or not
    */
    'isDefault'?: boolean;
    /**
    * The theme ID. If provided, the GUID will be used. Otherwise, the function will auto-create it.
    */
    'themeId'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "themeName",
            "baseName": "themeName",
            "type": "string"
        },
        {
            "name": "themeData",
            "baseName": "themeData",
            "type": "string"
        },
        {
            "name": "isDefault",
            "baseName": "isDefault",
            "type": "boolean"
        },
        {
            "name": "themeId",
            "baseName": "themeId",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ThemeApiObject.attributeTypeMap;
    }
}

