"use strict";
/**
 * Pyramid Analytics Web API
 * Pyramid Analytics Web API enables user applications to manage their pyramid                                             data and settings
 *
 * The version of the OpenAPI document: 2023.12.181
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.UpdateUserOpenIdObject = void 0;
/**
* The object used to update a OpenID user.
*/
var UpdateUserOpenIdObject = /** @class */ (function () {
    function UpdateUserOpenIdObject() {
        /**
        * Value used to determine the type of the item receiving, use the class name
        */
        this['inheritanceType'] = 'UpdateUserOpenIdObject';
    }
    UpdateUserOpenIdObject.getAttributeTypeMap = function () {
        return UpdateUserOpenIdObject.attributeTypeMap;
    };
    UpdateUserOpenIdObject.discriminator = undefined;
    UpdateUserOpenIdObject.attributeTypeMap = [
        {
            "name": "lastName",
            "baseName": "lastName",
            "type": "string"
        },
        {
            "name": "adminType",
            "baseName": "adminType",
            "type": "AdminType"
        },
        {
            "name": "proxyAccount",
            "baseName": "proxyAccount",
            "type": "string"
        },
        {
            "name": "clientLicenseType",
            "baseName": "clientLicenseType",
            "type": "ClientLicenseType"
        },
        {
            "name": "language",
            "baseName": "language",
            "type": "LanguageType"
        },
        {
            "name": "principalName",
            "baseName": "principalName",
            "type": "string"
        },
        {
            "name": "userName",
            "baseName": "userName",
            "type": "string"
        },
        {
            "name": "firstName",
            "baseName": "firstName",
            "type": "string"
        },
        {
            "name": "password",
            "baseName": "password",
            "type": "string"
        },
        {
            "name": "roleIds",
            "baseName": "roleIds",
            "type": "Set<string>"
        },
        {
            "name": "statusID",
            "baseName": "statusID",
            "type": "UserStatusID"
        },
        {
            "name": "profileType",
            "baseName": "profileType",
            "type": "UserProfileType"
        },
        {
            "name": "phone",
            "baseName": "phone",
            "type": "string"
        },
        {
            "name": "profileId",
            "baseName": "profileId",
            "type": "string"
        },
        {
            "name": "tenantId",
            "baseName": "tenantId",
            "type": "string"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "proxy2",
            "baseName": "proxy2",
            "type": "string"
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "string"
        },
        {
            "name": "inheritanceType",
            "baseName": "inheritanceType",
            "type": "string"
        }
    ];
    return UpdateUserOpenIdObject;
}());
exports.UpdateUserOpenIdObject = UpdateUserOpenIdObject;
