/**
 * Pyramid Analytics Web API
 * Pyramid Analytics Web API enables user applications to manage their pyramid                                             data and settings
 *
 * The version of the OpenAPI document: 2023.12.181
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* The user credentials for authentication by OpenID parameter map.
*/
export class UserOpenIdCredentials {
    /**
    * The URL web domain - needed only for embedded authentication.
    */
    'domain'?: string;
    /**
    * The OpenID token, you must specify either this or parameterMap which contains id_token with the same value.
    */
    'idToken'?: string;
    /**
    * Custom data input for usage within the product.
    */
    'customData'?: string;
    /**
    * The OpenID auth parameter map serialized to String.
    */
    'parameterMap'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "domain",
            "baseName": "domain",
            "type": "string"
        },
        {
            "name": "idToken",
            "baseName": "idToken",
            "type": "string"
        },
        {
            "name": "customData",
            "baseName": "customData",
            "type": "string"
        },
        {
            "name": "parameterMap",
            "baseName": "parameterMap",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return UserOpenIdCredentials.attributeTypeMap;
    }
}

