"use strict";
/**
 * Pyramid Analytics Web API
 * Pyramid Analytics Web API enables user applications to manage their pyramid                                             data and settings
 *
 * The version of the OpenAPI document: 2023.12.181
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.UserCredentials = void 0;
/**
* The user credential object used to set a user\'s login settings.
*/
var UserCredentials = /** @class */ (function () {
    function UserCredentials() {
    }
    UserCredentials.getAttributeTypeMap = function () {
        return UserCredentials.attributeTypeMap;
    };
    UserCredentials.discriminator = undefined;
    UserCredentials.attributeTypeMap = [
        {
            "name": "password",
            "baseName": "password",
            "type": "string"
        },
        {
            "name": "domain",
            "baseName": "domain",
            "type": "string"
        },
        {
            "name": "customData",
            "baseName": "customData",
            "type": "string"
        },
        {
            "name": "username",
            "baseName": "username",
            "type": "string"
        }
    ];
    return UserCredentials;
}());
exports.UserCredentials = UserCredentials;
