/**
 * Pyramid Analytics Web API
 * Pyramid Analytics Web API enables user applications to manage their pyramid                                             data and settings
 *
 * The version of the OpenAPI document: 2023.12.181
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* User profile types
*/
export enum UserProfileType {
    None = <any> 'None',
    Default = <any> 'Default',
    InheritedByRoles = <any> 'InheritedByRoles',
    PrivateRole = <any> 'PrivateRole'
}
