"use strict";
/**
 * Pyramid Analytics Web API
 * Pyramid Analytics Web API enables user applications to manage their pyramid                                             data and settings
 *
 * The version of the OpenAPI document: 2023.12.181
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.UserPhone = void 0;
/**
* Describes User Phone details
*/
var UserPhone = /** @class */ (function () {
    function UserPhone() {
    }
    UserPhone.getAttributeTypeMap = function () {
        return UserPhone.attributeTypeMap;
    };
    UserPhone.discriminator = undefined;
    UserPhone.attributeTypeMap = [
        {
            "name": "phone",
            "baseName": "phone",
            "type": "string"
        },
        {
            "name": "userId",
            "baseName": "userId",
            "type": "string"
        }
    ];
    return UserPhone;
}());
exports.UserPhone = UserPhone;
